{tools/cli/deployment} の翻訳
angular/angular-ja pull request #1005
Opened 2024-12-01 03:31 UTC by darkss-xyzzy

## 翻訳・修正

- [X] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/main/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue

https://github.com/angular/angular-ja/issues/1003

### 備考

・用語にゆらぎがないか
・各説明の解釈が誤っていないか
・英語ドキュメントで`_server_`となっていた箇所は、アンダースコアを使った記法だと、前後に半角スペースを入れないとイタリック体にならないため、`*サーバー*`と訳しましたので、問題ないか確認お願いします。

2024-12-01 09:30 UTC, lacolaco requested changes
翻訳ありがとうございます！コメントした部分の修正をお願いします :bow:

> 英語ドキュメントで_server_となっていた箇所は、アンダースコアを使った記法だと、前後に半角スペースを入れないとイタリック体にならないため、*サーバー*と訳しましたので、問題ないか確認お願いします。

こちらについては問題ありません。対応ありがとうございます。

2024-12-01 09:30 UTC, lacolaco commented on adev-ja/src/content/tools/cli/deployment.md
> +あなたのアプリケーションを手動でデプロイする場合、プロダクションビルドを作成し、出力ディレクトリをwebサーバーかcontent delivery network(CDN)にコピーしてください。
```suggestion
あなたのアプリケーションを手動でデプロイする場合、プロダクションビルドを作成し、出力ディレクトリをwebサーバーかコンテンツデリバリネットワーク(CDN)にコピーしてください。
```

Wikipedia記事もカタカナでありましたので、カタカナにしておきましょう

2024-12-01 09:30 UTC, lacolaco commented on adev-ja/src/content/tools/cli/deployment.md
> +ルーティングされたアプリケーションは「深いリンク」をサポートするべきです。
```suggestion
ルーティングされたアプリケーションは「ディープリンク」をサポートするべきです。
```

ディープリンクは一般名詞としてよいと思います。

2024-12-01 09:30 UTC, lacolaco commented on adev-ja/src/content/tools/cli/deployment.md
> +*深いリンク*はアプリケーションの中のコンポーネントへの経路を指定したURLです。
```suggestion
*ディープリンク*はアプリケーションの中のコンポーネントへの経路を指定したURLです。
```

2024-12-01 09:30 UTC, lacolaco commented on adev-ja/src/content/tools/cli/deployment.md
> +例えば、`http://my-app.test/users/42`は`id`42のユーザーを表示するユーザー詳細ページへの*深いリンク*です。
```suggestion
例えば、`http://my-app.test/users/42`は`id`42のユーザーを表示するユーザー詳細ページへの*ディープリンク*です。
```

2024-12-01 09:30 UTC, lacolaco commented on adev-ja/src/content/tools/cli/deployment.md
> +しかし、email内の深いリンクをクリックしたり、ブラウザのアドレスバーに深いリンクを入力したり、既に深いリンクに紐づけられたページをブラウザでリフレッシュするときさえも、実行しているアプリケーションの*外部*ですべてブラウザそのものによって処理されます。
```suggestion
しかし、電子メール内の深いリンクをクリックしたり、ブラウザのアドレスバーにディープリンクを入力したり、既にディープリンクに紐づけられたページをブラウザでリフレッシュするときさえも、実行しているアプリケーションの*外部*ですべてブラウザ自身によって処理されます。
```

2024-12-01 09:30 UTC, lacolaco commented on adev-ja/src/content/tools/cli/deployment.md
> +フォールバックルートを設定するか、サーバー上で404ページを`index.html`にする設定することで、Angularは深いリンクに関するサービスを提供し、正しいルートを表示することができます。
```suggestion
フォールバックルートを設定するか、サーバー上で404ページを`index.html`にする設定することで、Angularはディープリンクに関するサービスを提供し、正しいルートを表示することができます。
```

2024-12-01 09:30 UTC, lacolaco commented on adev-ja/src/content/tools/cli/deployment.md
> +いくつかのサーバーはこのフォールバックの挙動を"Single-Page Application"(SPA)モード呼びます。
```suggestion
いくつかのサーバーはこのフォールバックの挙動を"Single-Page Application"(SPA)モードと呼びます。
```

2024-12-01 09:30 UTC, lacolaco commented on adev-ja/src/content/tools/cli/deployment.md
> +*サーバー*はアプリケーションのリクエスト受諾するよう設定されていなければなりません。
```suggestion
*サーバー*はアプリケーションのリクエストを受け付けるよう設定されていなければなりません。
```

2024-12-01 09:30 UTC, lacolaco commented on adev-ja/src/content/tools/cli/deployment.md
> +プロダクションの最適化
```suggestion
## プロダクション最適化
```

2024-12-01 09:30 UTC, lacolaco commented on adev-ja/src/content/tools/cli/deployment.md
> +`ng build`は特に設定を行わない限り`production`を使います。この設定はビルド最適化機能を有効にします。
```suggestion
`ng build`は特に設定を行わない限り`production`設定を使います。この設定はビルド最適化機能を有効にします。
```

2024-12-01 11:21 UTC, darkss-xyzzy commented on adev-ja/src/content/tools/cli/deployment.md
> +しかし、email内の深いリンクをクリックしたり、ブラウザのアドレスバーに深いリンクを入力したり、既に深いリンクに紐づけられたページをブラウザでリフレッシュするときさえも、実行しているアプリケーションの*外部*ですべてブラウザそのものによって処理されます。
69行目のSuggested changeですが、
>しかし、電子メール内の深いリンクをクリックしたり、

「深いリンク」を「ディープリンク」に変更するのが正しいですよね。
再度プッシュした内容はディープリンクにしておきました。

同様に74行目の
>Angularは深いリンクに関するサービスを提供し、

も「深いリンク」を「ディープリンク」に変更する必要があると思いましたので、
Suggested changeには挙がっていませんでしたがこちらで対応しておきました。

2024-12-01 11:22 UTC, darkss-xyzzy commented on adev-ja/src/content/tools/cli/deployment.md
> +`ng serve`を使ってローカルでアプリケーションを起動するとき、Angularは開発用の設定を使用することで、実行時に以下が使用可能になります:
>Angularは開発用の設定を使用することで、

と
>実行時に以下が使用可能になります:

の間で改行を入れましたが、これで良いでしょうか。

2024-12-01 11:25 UTC, darkss-xyzzy commented
レビューしていただきありがとうございました。
指摘は反映したのですが、
69行目のSuggested changeと108行目の改行の件に関しては、
こちらからもコメントを入れましたので、
特に確認いただければと思います。

2024-12-02 13:59 UTC, lacolaco commented on adev-ja/src/content/tools/cli/deployment.md
> +いくつかのサーバーはこのフォールバックの挙動を"Single-Page Application"(SPA)モード呼びます。
こちらの脱字も修正をお願いします

2024-12-02 14:10 UTC, darkss-xyzzy commented on adev-ja/src/content/tools/cli/deployment.md
> +いくつかのサーバーはこのフォールバックの挙動を"Single-Page Application"(SPA)モード呼びます。
すみません、こちらのコメントを見逃していました。
脱字を修正しましたので、再度の確認をお願いします。

2024-12-02 14:57 UTC, lacolaco approved these changes
修正ありがとうございました！

2024-12-03 00:25 UTC, merged