translate: /guide/template-typecheck (#562)
angular/angular-ja pull request #573
Opened 2020-09-14 12:43 UTC by cleverdog

## 翻訳・修正

- [x] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/master/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue

#562 

### 備考

レビューのほどよろしくお願い申し上げます。

2020-09-17 00:51 UTC, lacolaco requested changes
翻訳ありがとうございます！コメントした部分の修正をお願いします :bow:

2020-09-17 00:51 UTC, lacolaco commented on aio-ja/content/guide/template-typecheck.md
> +# テンプレートの型チェック
`の` は無くてもよいかなと思います。テンプレート型チェック、でひとつの名詞としてよいかと。

2020-09-17 00:51 UTC, lacolaco commented on aio-ja/content/guide/template-typecheck.md
> +* 安全なナビゲーション式。
https://angular.jp/guide/template-expression-operators#safe-navigation-operator
セーフナビゲーション演算子にならい、「セーフナビゲーション式」としましょうか

2020-09-17 00:51 UTC, lacolaco commented on aio-ja/content/guide/template-typecheck.md
> +### ストリクトモード
「厳格モード」のほうが馴染みがよさそうです

2020-09-17 00:51 UTC, lacolaco commented on aio-ja/content/guide/template-typecheck.md
> +これらのエラーは、多くの場合、以前のツールでは検出されなかった、テンプレート内の正真正銘のな型の不一致を表しています。
```suggestion
これらのエラーは、多くの場合、以前のツールでは検出されなかった、テンプレート内の正真正銘の型の不一致を表しています。
```

2020-09-17 00:51 UTC, lacolaco commented on aio-ja/content/guide/template-typecheck.md
> +これが発生した場合は、[問題を報告](https://github.com/angular/angular/issues) して、チームが対処できるようにしてください。
すこし命令のような感じがするので、やわらかくしたほうがいいですね
```suggestion
これが発生した場合は、ぜひ[問題を報告](https://github.com/angular/angular/issues) して、開発チームが対処できるようにしてください。
```

2020-09-19 00:50 UTC, cleverdog commented
@lacolaco ご確認、FBありがとうございます。修正を反映いたしましたので再度ご確認のほどよろしくお願いします 🙇

2020-09-19 23:17 UTC, lacolaco approved these changes
修正ありがとうございます！マージさせていただきます！

2020-09-19 23:27 UTC, lacolaco commented
@googlebot I consent.

2020-09-20 00:23 UTC, merged