translate: guide/strict-mode.md
angular/angular-ja pull request #594
Opened 2020-11-26 14:35 UTC by big-stream

## 翻訳・修正

- [x] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/master/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue

#593 

レビューよろしくお願いいたします。

2020-11-28 01:39 UTC, lacolaco requested changes
翻訳ありがとうございます！コメントしました！

2020-11-28 01:39 UTC, lacolaco commented on aio-ja/content/guide/strict-mode.md
> +このフラグを有効にすると、新規のワークスペースやアプリケーションがいくつかの新しい設定で初期化します。これは、保守性を向上させ事前にバグを取るのに役立つものです。
```suggestion
このフラグを有効にすると、新規のワークスペースやアプリケーションがいくつかの新しい設定で初期化します。これは、保守性を向上させ事前にバグを検知するのに役立つものです。
```

取ることはできないのでcatchは検知とするのがよいかとおもいます

2020-11-28 01:39 UTC, lacolaco commented on aio-ja/content/guide/strict-mode.md
> +特に、`strict`フラグは次のことを行います:
```suggestion
具体的に、`strict`フラグは次のことを行います:
```

2020-11-29 14:09 UTC, big-stream commented
2か所訂正しました。

2020-11-30 10:43 UTC, lacolaco approved these changes
修正ありがとうございます！mergeさせていただきます！

2020-11-30 10:44 UTC, merged