translated: guide/form-validation.mdの翻訳
angular/angular-ja pull request #612
Opened 2021-02-06 15:17 UTC by nzzzz27

## 翻訳・修正

- [x] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/master/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue
https://github.com/angular/angular-ja/issues/603

レビューよろしくお願いいたします。

2021-02-06 15:38 UTC, nzzzz27 commented
@googlebot I signed it!

2021-02-08 00:37 UTC, lacolaco requested changes
翻訳ありがとうございます！コメントした部分の修正をお願いします :bow:

2021-02-08 00:37 UTC, lacolaco commented on aio-ja/content/guide/form-validation.md
> +* [TypeScript](https://www.typescriptlang.org/docs/home.html "TypeScript")とHTML5を使ったプログラミング。
こちら、参照先のURLは元のままが正しそうです

2021-02-08 00:37 UTC, lacolaco commented on aio-ja/content/guide/form-validation.md
> +<live-example></live-example>を起動する。
```suggestion
<live-example></live-example>を起動しましょう。
```

2021-02-08 00:37 UTC, lacolaco commented on aio-ja/content/guide/form-validation.md
> +INVALIDステータスに起因するバリデーションエラーのリスト、あるいはVALIDステータスに起因するnullを返します。
results in は `という結果になる` という意味なので、逆ですね
```suggestion
INVALIDステータスになるバリデーションエラーのリスト、あるいはVALIDステータスになるnullを返します。
```

2021-02-08 00:37 UTC, lacolaco commented on aio-ja/content/guide/form-validation.md
> +カスタムバリデーションディレクティブは、`useClass`ではなく`useExisting`でインスタンス化されることに注意してください。登録されたバリデーターは、`ForbiddenValidatorDirective`_インスタンス_でなければなりません。&mdash;`forbiddenName`プロパティを含むそのフォームのインスタンスは、
こちら1つ改行を加えて揃えてもらいたいです

2021-02-08 00:37 UTC, lacolaco commented on aio-ja/content/guide/form-validation.md
> -```
この削除は元に戻す必要がありそうです

2021-02-15 12:31 UTC, nzzzz27 commented
@lacolaco 
レビューありがとうございます！コメントいただいた部分を修正しました。
お手数ですが、ご確認をお願いいたします 🙇

2021-02-15 13:53 UTC, lacolaco approved these changes
修正ありがとうございます！mergeさせていただきます！

2021-02-15 13:57 UTC, merged