軽微な修正: start/start-routing.md
angular/angular-ja pull request #628
Opened 2021-03-30 01:58 UTC by yokotani92

以下修正させていただきました。
- 不自然な助詞を修正
- インラインのcodeの開始バッククォートが欠けていたので追加

## 翻訳・修正

- [x] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/master/CONTRIBUTING.md) に記載されたワークフローに従っています

2021-03-31 00:20 UTC, lacolaco requested changes
修正ありがとうございます！コメントした部分の修正をお願いします :bow:

2021-03-31 00:20 UTC, lacolaco commented on aio-ja/content/start/start-routing.md
> +1. コンストラクターの括弧内に引数として `private route. ActivatedRoute` を追加し、`ActivatedRoute` を `constructor()` に注入する。
原文は

> Inject ActivatedRoute into the constructor() by adding private route: ActivatedRoute as an argument within the constructor's parentheses.

になってましたね。たしかにこの通りです！

2021-03-31 00:20 UTC, lacolaco commented on aio-ja/content/start/start-routing.md
> +1. コンストラクターの括弧内に引数として `private route. ActivatedRoute` を追加し、`ActivatedRoute` を `constructor()` に注入する。
記号が間違っているのでそこだけ修正反映をお願いします
```suggestion
1. コンストラクターの括弧内に引数として `private route: ActivatedRoute` を追加し、`ActivatedRoute` を `constructor()` に注入する。
```

2021-03-31 13:56 UTC, yokotani92 commented on aio-ja/content/start/start-routing.md
> +1. コンストラクターの括弧内に引数として `private route. ActivatedRoute` を追加し、`ActivatedRoute` を `constructor()` に注入する。
ご指摘ありがとうございます。記号の間違い修正しました。

2021-04-01 00:40 UTC, lacolaco approved these changes
修正ありがとうございます！

2021-04-01 00:40 UTC, merged