translate: guide/what-is-angular.md
angular/angular-ja pull request #634
Opened 2021-04-16 08:58 UTC by shioyang

## 翻訳・修正

- [ ] 変更内容は [CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/master/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue

#633 

### 備考

これらは翻訳に悩んだところです。
- 15  行目
  - 埋めこまれる `<live-example name="what-is-angular"></live-example>` は翻訳の必要がありますか？どのファイルを編集する必要がありますか？
- 77 行目
  - `listen` → 待ち受けて
- 122 行目
  - `we strongly recommend it as a best practice and many aspects of Angular take advantage of it to some degree.` → ベストプラクティスとしてAngularの多くの側面である程度使用しているので、理解しておくことを強くお勧めします。
- 180 行目
  - `form participation` → 原文の直訳で「フォームの参加」としていますがよくわかっていないです
- 207 行目
  - リンク先を調整： `(https://angular.io/start)` → `(start)`
- 209 行目
  - 原文にはないリンク先を追加： `[Angularを理解する](guide/component-overview)と[開発者ガイド](guide/router)`

2021-04-16 09:01 UTC, shioyang commented
lint でエラー出てますね。修正します。

2021-04-16 11:00 UTC, shioyang commented
@lacolaco 修正しました。review お願いします。

2021-04-17 06:55 UTC, lacolaco requested changes
翻訳ありがとうございます！コメントした部分の修正をお願いします :bow:

2021-04-17 06:55 UTC, lacolaco commented on aio-ja/content/guide/what-is-angular.md
> +* 拡張可能なウェブアプリケーションを構築するためのコンポーネントベースのフレームワーク
拡張可能というとextensibleのようなニュアンスも含まれるので、そのままスケーラブルとしましょう

```suggestion
* スケーラブルなウェブアプリケーションを構築するためのコンポーネントベースのフレームワーク
```

2021-04-17 06:55 UTC, lacolaco commented on aio-ja/content/guide/what-is-angular.md
> +Angularは、コンポーネントから動的な値を挿入できる追加の構文でHTMLを拡張します。コンポーネントの状態が変化すると、AngularはレンダリングされたDOMを自動的に更新します。次の例に示すように、この機能を使ったひとつのアプリケーションは、動的にテキストを挿入することです。
このOne applicationはコンピュータ文脈のアプリケーションではなく応用という一般的な語彙ですね

```suggestion
Angularは、コンポーネントから動的な値を挿入できる追加の構文でHTMLを拡張します。コンポーネントの状態が変化すると、AngularはレンダリングされたDOMを自動的に更新します。次の例に示すように、この機能の応用例のひとつは動的なテキストの挿入です。
```

2021-04-17 06:55 UTC, lacolaco commented on aio-ja/content/guide/what-is-angular.md
> +セクション[Angularアプリケーション：基本事項](#essentials)では、Angularアプリケーションを構築するときに使用するいくつかの主要なアーキテクチャ要素の概要を説明しています。しかし、Angularの多くの利点は、アプリケーションが成長し、サイトナビゲーションやユーザー入力などの機能を追加したいときに実際に明らかになります。そのとき、Angularプラットフォームを活用して
同じ意味ですので削ったほうが自然そうです

```suggestion
[Angularアプリケーション：基本事項](#essentials)では、Angularアプリケーションを構築するときに使用するいくつかの主要なアーキテクチャ要素の概要を説明しています。しかし、Angularの多くの利点は、アプリケーションが成長し、サイトナビゲーションやユーザー入力などの機能を追加したいときに実際に明らかになります。そのとき、Angularプラットフォームを活用して、Angularが提供する多くのファーストパーティライブラリのひとつを組み込むことができます。
```

2021-04-17 06:55 UTC, lacolaco commented on aio-ja/content/guide/what-is-angular.md
> +<td>フォームへの参加と検証のための統一されたシステム。</td>
ここは `participation` のニュアンスが難しいですが、フォームへの介入というのが自然そうです

```suggestion
<td>フォームへの介入と検証のための統一されたシステム。</td>
```

2021-04-17 06:55 UTC, lacolaco commented on aio-ja/content/guide/what-is-angular.md
> +<td>アプリケーションの状態に基づいてアニメーションを駆動するための豊富なシステム。</td>
```suggestion
<td>アプリケーションの状態に基づいてアニメーションを駆動するリッチなシステム。</td>
```

2021-04-17 06:55 UTC, lacolaco commented on aio-ja/content/guide/what-is-angular.md
> +<td>ServiceWorkerやWebアプリのマニフェストなどのプログレッシブWebアプリケーション（PWA）を構築するためのツール。</td>
```suggestion
<td>Service WorkerやWebアプリマニフェストを含むプログレッシブWebアプリケーション（PWA）を構築するためのツール。</td>
```

2021-04-17 06:55 UTC, lacolaco commented on aio-ja/content/guide/what-is-angular.md
> +# Angularとは何でしょうか？
タイトルなので簡潔にしたいです

```suggestion
# Angularとは何か？
```

2021-04-17 06:57 UTC, lacolaco commented
> 15 行目
> 埋めこまれる `<live-example name="what-is-angular"></live-example>` は翻訳の必要がありますか？どのファイルを編集する必要がありますか？

一旦はこのままでいいです！

2021-04-17 10:57 UTC, shioyang commented
review ありがとうございます。確認して修正します。

2021-04-18 10:34 UTC, shioyang commented
@lacolaco  review & suggestions ありがとうございました。確認して適用しました。

2021-04-21 09:09 UTC, lacolaco approved these changes
修正ありがとうございます！

2021-04-21 09:09 UTC, merged