translate: guide/http.md
angular/angular-ja pull request #670
Opened 2021-06-27 15:56 UTC by knts0

## 翻訳・修正

- [x] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/master/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue
https://github.com/angular/angular-ja/issues/665

### 備考
- 重点的にレビューをお願いしたい点
  - 原文L488の「As for」の訳
  - 原文L557「in a routine, standard way」の訳
  - 原文L691「rendering them largely immutable」の訳

2021-06-27 16:19 UTC, knts0 commented
@googlebot I signed it!

2021-06-27 17:03 UTC, knts0 commented on aio-ja/content/guide/http.md
> +# HTTPによるバックエンドサービスとの通信
なぜか原文側のタイトルが消えてしまっていますね…
原因は特定できていませんが、fork先に最新版の取り込みを行った際におかしなことになってしまったかもしれません。
少なくとも`angular:master`のこのファイルには存在しています。https://github.com/angular/angular-ja/blob/master/aio-ja/content/guide/http.md

2021-07-08 14:13 UTC, lacolaco requested changes
レビュー遅くなってしまいました。翻訳ありがとうございます！コメントした部分の修正をお願いします :bow:
気にされている3つの点は不自然さは感じませんでしたのでこのままでいいと思います。

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +インターセプト無しでは、開発者は各`HttpClient`メソッド呼び出しに対してこれらのタスクを_明示的に_実装する必要があります。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +この必須設定は、Angularに`HTTP_INTERCEPTORS`は単一の値ではなく値の配列を注入する_マルチプロバイダー_のトークンであることを伝えます。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +また、これらのインターセプターを提供する[順序に細心の注意](#interceptor-order)を払う必要があります。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +{@a interceptor-order}
アンカーの追加は見出しと同じ行に追加してください

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +これは、トークンを取得するサービスを注入し、トークンをすべての外部へのリクエストの認可ヘッダーに追加する、`AuthInterceptor`です。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +これは、リクエストの時間とレスポンスの時間を取得し、注入された`MessageService`で経過時間とともに結果を記録します。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +* リクエストがキャッシュ可能でない場合、インターセプターはリクエストをチェーン内の次のハンドラーに転送します。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +* キャッシング可能なリクエストがキャッシュ内に見つかった場合、インターセプターはキャッシュされたレスポンスを`of()`_Observable_で返し、`next`ハンドラー（および他のすべての下流のインターセプター）をバイパスします。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +元のレスポンスは、インターセプターのチェーンを通ってアプリケーション呼び出し元にオリジナルの状態で戻ります。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +`PackageSearchService`のようなデータサービスは、`HttpClient`リクエストのいくつかは実際にはキャッシュされたレスポンスを返すものがあることを知りません。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +`results$`Observableは、サブスクライブ時にリクエストを行います。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +サブスクライバーは、連続の2つのレスポンスを参照します。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +シミュレートされたイベントのObservableを返します。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +ユーザーが検索ボックスに名前を入力すると、`PackageSearchComponent`はその名前のパッケージの検索リクエストをnpm Web APIに送信します。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +これは、RxJSの`Subject`として定義されています。`Subject`は、`search()`メソッドで行っているように、`next(value)`を呼び出すことによって、自身に対して値を発行できるマルチキャスト`Observable`です。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +サービスのレスポンスをサーバーが順不同で返したとしても、`switchMap()`は、元のリクエストの順序で返すことに注意してください。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +{@a security-xsrf-protection}
アンカーの追加は見出しと同じ行に追加してください

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +デフォルトでは、インターセプターは相対URLへのすべての変更リクエスト（POSTなど）に対してこのヘッダーを送信しますが、GET/HEADリクエストや絶対URLには送りません。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +{@a testing-http-requests}
既存のアンカーは変えないようお願いします

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +ライブコーディング環境で<live-example stackblitz="specs">これらのサンプルテスト</live-example>を実行できます。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +`src/app/heroes/heroes.service.spec.ts`に`HttpClient`を呼び出すアプリケーションデータサービスのテストもあります。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +`HttpClientTestingModule`とモックコントローラ`HttpTestingController`を、テストに必要な他のシンボルと共にインポートしてください。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +次に`HttpClientTestingModule`を`TestBed`に追加し、_テスト環境下のサービス_の設定を続けます。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +以前の`expectOne()`と同様に、0または2以上のリクエストがこの条件を満たしていれば、テストは失敗します。
改行数がずれているので合わせていただけますか？

2021-07-08 14:13 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +インターセプターは、すべてのHTTPリクエスト/レスポンスに対して、認証からロギングまで、さまざまな_暗黙の_タスクを型どおりの、標準的な方法で実行できます。
👍

2021-07-15 13:46 UTC, lacolaco commented
@knts0 修正できそうでしょうか？

2021-07-16 08:57 UTC, knts0 commented
@lacolaco 
レス遅れすみません！今週末に修正します 🙇‍♀️

2021-07-17 10:04 UTC, knts0 commented on aio-ja/content/guide/http.md
> +* 簡素化された[エラーハンドリング](#error-handling)
修正いたしました。https://github.com/angular/angular-ja/pull/670/commits/bd216363ecc17b390c4e80fe8fed2dfb592a8ba6

2021-07-17 10:05 UTC, knts0 commented on aio-ja/content/guide/http.md
> +* [テスタビリティ](#testing-http-requests)
失礼しました。修正いたしました。https://github.com/angular/angular-ja/pull/670/commits/0ecdc2eefe57ec984c5061d02c940c3ada3ef420

2021-07-17 10:05 UTC, knts0 commented on aio-ja/content/guide/http.md
> +{@a testing-http-requests}
失礼しました。修正いたしました。0ecdc2e

2021-07-17 12:49 UTC, knts0 commented on aio-ja/content/guide/http.md
> +サーバーが[CORSプロトコル](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)をサポートしていない場合、アプリケーションは`HttpClient`を使用してドメインをまたいで[JSONP](https://en.wikipedia.org/wiki/JSONP)リクエストを実行できます。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/eaabca0f82d89875b9bfcb3315a612e6227e4987

2021-07-17 12:51 UTC, knts0 commented on aio-ja/content/guide/http.md
> +**いつも_subscribe_!**
修正しました。https://github.com/angular/angular-ja/pull/670/commits/afee116d086f82ceea18eaa4d44ce84b9d42582b

2021-07-17 12:55 UTC, knts0 commented on aio-ja/content/guide/http.md
> +* [テスタビリティ](#testing-http-requests)
こちらなのですが、[testing-services.md](https://github.com/knts0/angular-ja/blob/http/aio-ja/content/guide/testing-services.md)から参照されているリンクが`guide/http#testing-http-requests`になっており、ビルドが通らなかったため修正したのでした 🙇‍♀️

2021-07-17 12:57 UTC, knts0 commented on aio-ja/content/guide/http.md
> +この代わりのサービスはRESTのようなバックエンドの振る舞いをシミュレートしたものです。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R54

2021-07-17 12:57 UTC, knts0 commented on aio-ja/content/guide/http.md
> +`ConfigService`の例では、アプリケーションはリソースURLを指定する `config.json`という設定ファイルが必要です。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R97

2021-07-17 12:57 UTC, knts0 commented on aio-ja/content/guide/http.md
> +更新されたコンポーネントメソッドのコールバックは、型付けされたデータオブジェクトを受け取ります。これは使用がより簡単で安全です。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R172

2021-07-17 12:57 UTC, knts0 commented on aio-ja/content/guide/http.md
> +次のセクションでは、サンプルの`HeroesService`からのデータ更新メソッドの例を示します。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R374

2021-07-17 12:58 UTC, knts0 commented on aio-ja/content/guide/http.md
> +`HeroesComponent`がこのサービスのメソッドが返す`Observable`を購読することによって、実際のPOST処理が開始します。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R396

2021-07-17 12:58 UTC, knts0 commented on aio-ja/content/guide/http.md
> +サーバーが新しく追加されたヒーローを正常に返すと、コンポーネントはそのヒーローを画面に表示されている`heroes`リストに追加します。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R405

2021-07-17 12:58 UTC, knts0 commented on aio-ja/content/guide/http.md
> +このアプリケーションは、リクエストURLにヒーローのIDを渡すことによって、`HttpClient.delete`メソッドを使用してヒーローを削除します。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R410

2021-07-17 12:58 UTC, knts0 commented on aio-ja/content/guide/http.md
> +`HeroesComponent`がこのサービスのメソッドが返す`Observable`を購読することによって、実際のDELETE処理が開始します。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R419

2021-07-17 12:58 UTC, knts0 commented on aio-ja/content/guide/http.md
> +HTTPリクエストは_遅延実行_され、実際に何かが起こる前に、`tap`や`catchError`などの追加のオペレーターでObservableを拡張できます。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R454

2021-07-17 12:59 UTC, knts0 commented on aio-ja/content/guide/http.md
> +{@a adding-headers}
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R495

2021-07-17 12:59 UTC, knts0 commented on aio-ja/content/guide/http.md
> +`HeroesService`は、`HttpClient`の保存メソッドすべてに渡される`httpOptions`オブジェクトで、そのようなヘッダーを定義しています。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R497

2021-07-17 12:59 UTC, knts0 commented on aio-ja/content/guide/http.md
> +インターセプト無しでは、開発者は各`HttpClient`メソッド呼び出しに対してこれらのタスクを_明示的に_実装する必要があります。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R559

2021-07-17 12:59 UTC, knts0 commented on aio-ja/content/guide/http.md
> +この必須設定は、Angularに`HTTP_INTERCEPTORS`は単一の値ではなく値の配列を注入する_マルチプロバイダー_のトークンであることを伝えます。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R620

2021-07-17 13:00 UTC, knts0 commented on aio-ja/content/guide/http.md
> +また、これらのインターセプターを提供する[順序に細心の注意](#interceptor-order)を払う必要があります。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R624

2021-07-17 13:00 UTC, knts0 commented on aio-ja/content/guide/http.md
> +{@a interceptor-order}
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R654

2021-07-17 13:00 UTC, knts0 commented on aio-ja/content/guide/http.md
> +これは、トークンを取得するサービスを注入し、トークンをすべての外部へのリクエストの認可ヘッダーに追加する、`AuthInterceptor`です。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R766

2021-07-17 13:00 UTC, knts0 commented on aio-ja/content/guide/http.md
> +これは、リクエストの時間とレスポンスの時間を取得し、注入された`MessageService`で経過時間とともに結果を記録します。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R793

2021-07-17 13:00 UTC, knts0 commented on aio-ja/content/guide/http.md
> +* リクエストがキャッシュ可能でない場合、インターセプターはリクエストをチェーン内の次のハンドラーに転送します。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R861

2021-07-17 13:01 UTC, knts0 commented on aio-ja/content/guide/http.md
> +* キャッシング可能なリクエストがキャッシュ内に見つかった場合、インターセプターはキャッシュされたレスポンスを`of()`_Observable_で返し、`next`ハンドラー（および他のすべての下流のインターセプター）をバイパスします。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R864

2021-07-17 13:01 UTC, knts0 commented on aio-ja/content/guide/http.md
> +元のレスポンスは、インターセプターのチェーンを通ってアプリケーション呼び出し元にオリジナルの状態で戻ります。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R880

2021-07-17 13:01 UTC, knts0 commented on aio-ja/content/guide/http.md
> +`PackageSearchService`のようなデータサービスは、`HttpClient`リクエストのいくつかは実際にはキャッシュされたレスポンスを返すものがあることを知りません。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R883

2021-07-17 13:01 UTC, knts0 commented on aio-ja/content/guide/http.md
> +`results$`Observableは、サブスクライブ時にリクエストを行います。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R912

2021-07-17 13:02 UTC, knts0 commented on aio-ja/content/guide/http.md
> +サブスクライバーは、連続の2つのレスポンスを参照します。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R919

2021-07-17 13:02 UTC, knts0 commented on aio-ja/content/guide/http.md
> +シミュレートされたイベントのObservableを返します。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R971

2021-07-17 13:02 UTC, knts0 commented on aio-ja/content/guide/http.md
> +ユーザーが検索ボックスに名前を入力すると、`PackageSearchComponent`はその名前のパッケージの検索リクエストをnpm Web APIに送信します。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R984

2021-07-17 13:02 UTC, knts0 commented on aio-ja/content/guide/http.md
> +これは、RxJSの`Subject`として定義されています。`Subject`は、`search()`メソッドで行っているように、`next(value)`を呼び出すことによって、自身に対して値を発行できるマルチキャスト`Observable`です。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R1013

2021-07-17 13:03 UTC, knts0 commented on aio-ja/content/guide/http.md
> +サービスのレスポンスをサーバーが順不同で返したとしても、`switchMap()`は、元のリクエストの順序で返すことに注意してください。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R1043

2021-07-17 13:03 UTC, knts0 commented on aio-ja/content/guide/http.md
> +{@a security-xsrf-protection}
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R1055

2021-07-17 13:03 UTC, knts0 commented on aio-ja/content/guide/http.md
> +デフォルトでは、インターセプターは相対URLへのすべての変更リクエスト（POSTなど）に対してこのヘッダーを送信しますが、GET/HEADリクエストや絶対URLには送りません。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R1062

2021-07-17 13:04 UTC, knts0 commented on aio-ja/content/guide/http.md
> +ライブコーディング環境で<live-example stackblitz="specs">これらのサンプルテスト</live-example>を実行できます。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R1106

2021-07-17 13:04 UTC, knts0 commented on aio-ja/content/guide/http.md
> +`src/app/heroes/heroes.service.spec.ts`に`HttpClient`を呼び出すアプリケーションデータサービスのテストもあります。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R1110

2021-07-17 13:05 UTC, knts0 commented on aio-ja/content/guide/http.md
> +`HttpClientTestingModule`とモックコントローラ`HttpTestingController`を、テストに必要な他のシンボルと共にインポートしてください。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R1118

2021-07-17 13:05 UTC, knts0 commented on aio-ja/content/guide/http.md
> +次に`HttpClientTestingModule`を`TestBed`に追加し、_テスト環境下のサービス_の設定を続けます。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R1127

2021-07-17 13:05 UTC, knts0 commented on aio-ja/content/guide/http.md
> +以前の`expectOne()`と同様に、0または2以上のリクエストがこの条件を満たしていれば、テストは失敗します。
修正しました。https://github.com/angular/angular-ja/pull/670/commits/495ca94e41d3d553bcecb178958c52f76adb67b7#diff-b7191c59ef5dec20fbbb9a7cb2d56cf82a5ad9254fbe83b100f6b1450521f078R1168

2021-07-17 13:07 UTC, knts0 commented
@lacolaco 
レビューありがとうございました 🙇‍♀️ コメントいただいた点を修正しました！
改行位置についての理解ができておらずすみませんでした 🙇‍♀️ 
1点、アンカーについて他ドキュメントからの参照と異なっていてビルドが通らない点があったのでコメントを残しました。https://github.com/angular/angular-ja/pull/670#discussion_r671694254

2021-07-17 14:31 UTC, lacolaco commented on aio-ja/content/guide/http.md
> +## HTTPリクエストをテストする
原文の見出しがもともと `testing-http-requests` のアンカーになっていたのがなくなったのだと思いますので、この見出しと同じ行に後方互換のためのアンカーを追加してもらえるとよいです！

2021-07-17 15:08 UTC, knts0 commented on aio-ja/content/guide/http.md
> +## HTTPリクエストをテストする
@lacolaco 
なるほどです！対応しました。https://github.com/angular/angular-ja/pull/670/commits/98ba63405742a809f99688cd030e0e7aa7dc9cfa

2021-07-18 01:35 UTC, lacolaco approved these changes
修正ありがとうございます！mergeさせていただきます！

2021-07-18 01:39 UTC, merged