軽微な修正: guide/creating-libraries.md
angular/angular-ja pull request #680
Opened 2021-08-31 09:22 UTC by big-stream

## 翻訳・修正

- [x] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/master/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue

#486

よろしくお願いいたします。

2021-09-03 00:51 UTC, lacolaco requested changes
翻訳ありがとうございます！コメントした部分の修正をお願いします :bow:

2021-09-03 00:51 UTC, lacolaco commented on aio-ja/content/guide/creating-libraries.md
> +* ビューエンジン _(非推奨)_ &mdash; レガシー形式で、Angularバージョン13で削除される予定です。
ViewEngineはここでは固有名詞なのでView Engineのまま残しておきたいです

2021-09-03 00:51 UTC, lacolaco commented on aio-ja/content/guide/creating-libraries.md
> +この一例は[Angular Materialのnavigation schematic](https://material.angular.io/guide/schematics#navigation-schematic)です。これは、CDKの[BreakpointObserver](https://material.angular.io/cdk/layout/overview#breakpoi
ここで1行ずれているようです

2021-09-03 13:34 UTC, big-stream commented on aio-ja/content/guide/creating-libraries.md
> +この一例は[Angular Materialのnavigation schematic](https://material.angular.io/guide/schematics#navigation-schematic)です。これは、CDKの[BreakpointObserver](https://material.angular.io/cdk/layout/overview#breakpoi
103行目は、現在の原文に沿って、以前の翻訳になかった改行を入れています。ついでにこの当たりは翻訳し直しています。以前の翻訳時点から現在までに原文が多少変わったようです。

2021-09-03 13:36 UTC, big-stream commented on aio-ja/content/guide/creating-libraries.md
> +* ビューエンジン _(非推奨)_ &mdash; レガシー形式で、Angularバージョン13で削除される予定です。
他の箇所もView Engineに直しました。

2021-09-04 06:29 UTC, lacolaco commented on aio-ja/content/guide/creating-libraries.md
> +この一例は[Angular Materialのnavigation schematic](https://material.angular.io/guide/schematics#navigation-schematic)です。これは、CDKの[BreakpointObserver](https://material.angular.io/cdk/layout/overview#breakpoi
なるほど、了解しました！

2021-09-04 06:30 UTC, lacolaco approved these changes
修正ありがとうございます！

2021-09-04 06:30 UTC, merged