子コンポーネントにデータを渡すの章で説明が抜けているためエラーが起こる (英語のドキュメントと比較)
angular/angular-ja pull request #681
Opened 2021-09-18 07:47 UTC by aran-nakayama

エラー内容：
```
'app-product-alerts' is not a known element:

If 'app-product-alerts' is an Angular component, then verify that it is part of this module.
If 'app-product-alerts' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

## 翻訳・修正

- [ ] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/master/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue

### 備考

2021-09-18 07:51 UTC, aran-nakayama commented
@googlebot I signed it!

2021-09-19 07:29 UTC, lacolaco commented on aio-ja/content/start/index.md
> +1. `ProductAlertsComponent`を他のコンポーネント内でも使えるように、 `app.module.ts`内の`AppModule's　declarations`に追加する。
```suggestion
1. `ProductAlertsComponent`を他のコンポーネント内でも使えるように、 `app.module.ts`内の`AppModule`の　`declarations`に追加する。
```

2021-09-19 07:29 UTC, lacolaco requested changes
修正ありがとうございます！！コメントした点の修正をお願いします！

2021-09-21 12:27 UTC, aran-nakayama commented
suggestionありがとうございます！修正しました！

2021-09-21 13:52 UTC, lacolaco commented
こちらの変更で新たに参照するようになったサンプルコードが、まだこのリビジョンでは存在していないようです。
リポジトリ全体のアップデートをかけないといけないのでしばらくおまたせしますが、このプルリクエストを取り込める形にできるよう努力してみます。

2021-09-23 14:26 UTC, lacolaco commented
@aran-nakayama masterブランチを更新した結果、該当部分は追記されましたが英語のまま残してあります。
せっかくのコントリビューションですので、このプルリクエストをリベースしてコンフリクトを解消するか、あらためて別のプルリクエストで同じ部分の翻訳をしていただくことはできますか？

2021-09-30 01:02 UTC, aran-nakayama commented
@lacolaco 
ありがとうございます！

- #683 
- ↑こちらに再度作成いたしました！

2021-10-03 07:30 UTC, closed without merging