翻訳: guide/prerendering.md #679
angular/angular-ja pull request #685
Opened 2021-11-01 11:51 UTC by komura-c

## 翻訳・修正

- [x] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/master/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue
#679

### 備考
プリレンダリングか事前レンダリングで表記を統一するか悩んだのですが、どちらが適切でしょうか...？
よろしくお願いいたします！

2021-11-04 12:01 UTC, lacolaco requested changes
翻訳ありがとうございます！コメントした部分の修正をお願いします :bow:

2021-11-08 11:03 UTC, lacolaco commented
@komura-c こちら今週末までに修正していただくことできますでしょうか？
サイト全体のv13対応も控えているため、来週以降になりそうであればv13アップデート後にリベースしていただくことになります。

2021-11-08 12:02 UTC, komura-c commented
@lacolaco 
> 今週末までに修正

できます！修正してみましたのでお時間ある際に再度、ご確認お願いいたします！🙇‍♂️

2021-11-08 12:03 UTC, lacolaco commented
@komura-c ありがとうございます！マージに必要なのでGoogleのCLAにも同意いただけますか？

2021-11-08 12:12 UTC, komura-c commented
@googlebot I signed it!

2021-11-08 12:34 UTC, lacolaco commented
@komura-c testが失敗しているようです。
https://github.com/angular/angular-ja/runs/4138775499?check_suite_focus=true
エラー文の指示のとおりtextlint --fixの実行をお願いします！

2021-11-08 13:07 UTC, lacolaco commented
修正ありがとうございます！mergeさせていただきます！

2021-11-08 13:08 UTC, merged