translate: guide/i18n-common-prepare
angular/angular-ja pull request #713
Opened 2022-06-03 00:39 UTC by nishitaku

## 翻訳・修正

- [ ] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/master/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue

https://github.com/angular/angular-ja/issues/688

### 備考

2022-06-05 08:52 UTC, lacolaco commented
@nishitaku CIでビルドエラーになっているのはおそらくmasterブランチにrebaseしていただければ解決するので対応をお願いします

2022-06-06 01:17 UTC, nishitaku commented
@lacolaco 
修正しました！

2022-06-06 12:23 UTC, lacolaco requested changes
翻訳ありがとうございます！コメントした部分の修正をお願いします :bow:

2022-06-06 12:23 UTC, lacolaco commented on aio-ja/content/guide/i18n-common-prepare.md
> +*   `localize`タグ付きメッセージ文字列を使用して、コンポーネントコード内のテキスト文字列をマークします。
```suggestion
*   `$localize`タグ付きメッセージ文字列を使用して、コンポーネントコード内のテキスト文字列をマークします。
```

2022-06-06 12:23 UTC, lacolaco commented on aio-ja/content/guide/i18n-common-prepare.md
> +### 補間テキストを含む
```suggestion
### 補間テキストを含める
```

2022-06-06 12:23 UTC, lacolaco commented on aio-ja/content/guide/i18n-common-prepare.md
> +### 補間プレースホルダーの名称
```suggestion
### 補間プレースホルダーに名前をつける
```

2022-06-07 01:43 UTC, nishitaku commented on aio-ja/content/guide/i18n-common-prepare.md
> +### 補間テキストを含む
ご指摘ありがとうございます。修正しましたのでご確認ください。 2740292

2022-06-07 01:43 UTC, nishitaku commented on aio-ja/content/guide/i18n-common-prepare.md
> +### 補間プレースホルダーの名称
ご指摘ありがとうございます。修正しましたのでご確認ください。 2740292

2022-06-07 01:43 UTC, nishitaku commented on aio-ja/content/guide/i18n-common-prepare.md
> +*   `localize`タグ付きメッセージ文字列を使用して、コンポーネントコード内のテキスト文字列をマークします。
ご指摘ありがとうございます。修正しましたのでご確認ください。 2740292

2022-06-07 09:54 UTC, lacolaco approved these changes
修正ありがとうございます！マージさせていただきます！

2022-06-07 09:54 UTC, merged