translate: guide/devtools
angular/angular-ja pull request #778
Opened 2022-09-13 09:53 UTC by 2YY

## 翻訳・修正
* [x]  変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/master/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue
#766
 
### 備考
 
 * 原文L26・27・41・95・135・148・157・224・236・237: 実際に表示される UI 上の表記と統一されている方が混乱が無いかと思い、それらのタブやアイコンの名称は敢えて英語のままで残してみております。
   * L224 に関しては、実際のUI上の表記と英語原文との間でも差異が有ったため、`Show only change detection` にしてあげたい気もしますが・・
 * 原文L160: 上記対応の例外として、この行に関しては、日本語的におかしくなってしまいそうなため、UI 上では英語の部分も、和訳版では日本語の表記で反映しております。( `記録を停止` )
 * 原文L163: 原文の時点でリンク先がダミーとなっているため、後日、原文でリンクが修正された際に、和訳版も追従する必要がありそうです。
 * 原文L167: 機械翻訳そのままの状態で少し違和感が有ったため、やや意訳しております。
 * 原文L236: 原文では左上 ( `top-left` ) と記載されていますが、スクリーンショットの内容からも、右上の誤りであると思われるため、和訳版では右上と表記しております。

2022-09-13 15:27 UTC, lacolaco requested changes
翻訳ありがとうございます！コメントした部分の修正をお願いします :bow:

2022-09-13 15:27 UTC, lacolaco commented on aio-ja/content/guide/devtools.md
> +# 開発ツールの概要
DevTools は固有名詞として扱うほうが、他の文脈での検索などに一貫性がありそうです。Chrome DevToolsの日本語翻訳でもDevToolsはそのままなので、ファイル全体でそのまま残しましょう
```suggestion
# DevTools の概要
```

2022-09-13 15:27 UTC, lacolaco commented on aio-ja/content/guide/devtools.md
> +Angular 開発ツールは、[Chrome ウェブストア](https://chrome.google.com/webstore/detail/angular-developer-tools/ienfalfjdbdpebioblfackkekamfmbnh) と [Firefox アドオン](https://addons.mozilla.org/en-GB/firefox/addon/angu
```suggestion
Angular DevTools は、[Chrome ウェブストア](https://chrome.google.com/webstore/detail/angular-developer-tools/ienfalfjdbdpebioblfackkekamfmbnh) と [Firefox アドオン](https://addons.mozilla.org/en-GB/firefox/addon/angular-devtools/) で見つけられます。
```

2022-09-13 15:27 UTC, lacolaco commented on aio-ja/content/guide/devtools.md
> +### アプリケーション構造を調べる
```suggestion
### アプリケーションの構造を調べる
```

2022-09-13 15:27 UTC, lacolaco commented on aio-ja/content/guide/devtools.md
> +現在選択されているコンポーネントまたはディレクティブのインスタンスへの参照を取得するには `$ng0` と入力し、以前に選択したインスタンスの場合は `$ng1` と入力します。
```suggestion
現在選択されているコンポーネントまたはディレクティブのインスタンスへの参照を取得するには `$ng0` と入力し、その前に選択したインスタンスの場合は `$ng1` と入力します。
```

2022-09-13 15:27 UTC, lacolaco commented on aio-ja/content/guide/devtools.md
> +開発ツールは、変更検知にもっとも多くの時間を費やしたタイルと比較して、費やした時間によって色の強度を決定します。
```suggestion
DevTools は、変更検知にもっとも時間をかけたタイルとの相対的な時間によって、色の濃さを決定します。
```

2022-09-13 15:27 UTC, lacolaco commented on aio-ja/content/guide/devtools.md
> +Angular が検出を変更したコンポーネントをプレビューするには、フレームグラフの上にある **Change detection** チェックボックスを選択します。
```suggestion
Angular が変更を検知したコンポーネントをプレビューするには、フレームグラフの上にある **Change detection** チェックボックスを選択します。
```

2022-09-14 03:43 UTC, 2YY commented
レビュー頂き有難うございます！
コメント頂いた箇所の修正が出来ましたので、ご確認をお願いいたします！

2022-09-14 03:44 UTC, 2YY commented on aio-ja/content/guide/devtools.md
> +# 開発ツールの概要
L1 のみ、
おそらくサイト全体的に、見出し内の英単語の左右に半角スペースを空けない方式になっていそうであったため、
「s」と「の」の間は詰めた状態で修正反映させて頂きました、問題有れば再修正致します！

また、下記にも同じものを指す `開発ツール` という表記が有るため、もしかすると統一してあげても良いのかもしれません。
(一旦、特に触れずとしておりますが、この PR で直して良いものであれば、修正致します！)
https://angular.jp/guide/roadmap
https://angular.jp/guide/service-worker-devops

下記にも `開発ツール` という表記が有りますが、これらは VSCode のようなエディタ等も含意していそうなため、
少しニュアンスが違いそう (= `DevTools` に書き換える必要は無い) かもしれません。
https://angular.jp/guide/upgrade
https://angular.jp/guide/workspace-config
https://angular.jp/guide/glossary
https://angular.jp/guide/universal

2022-09-14 04:10 UTC, 2YY commented
(すみません、一箇所対応漏れが有ったため、もう 1 つコミット追加しております)

2022-09-14 04:14 UTC, lacolaco commented on aio-ja/content/guide/devtools.md
> +# 開発ツールの概要
一般語彙として開発者ツールや開発ツールと、固有名詞としてのDevToolsを機械的に区別するのは難しいので、都度判断になりそうです
他の場所についてはいったんこのPRでは触れず、別のIssueとして上げておいてもらえると助かります！

2022-09-14 04:20 UTC, lacolaco approved these changes
修正ありがとうございます！mergeさせていただきます！

2022-09-14 07:41 UTC, merged