translate: guide/change-detection-zone-pollution
angular/angular-ja pull request #781
Opened 2022-09-14 14:12 UTC by kasaharu

## 翻訳・修正

- [x] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/main/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue

#759

### 備考

- L.1 Zone Pollution: `Zone 汚染` と翻訳したが `汚染` のニュアンスが強すぎないか気になりました(が他の訳が思いつかず…)
- L.24 given piece of code: `指定されたコード片` とするには違和感があったので `piece of` の意味が欠けていますが `指定されたコード` と翻訳しました
- L.37 Angular Zone: 原文の表記ゆれです。(L.9, L.39 と異なり)ここだけ `Angular Zone` の Z が大文字でしたがそのまま翻訳しています

2022-09-16 12:34 UTC, lacolaco commented
@kasaharu 翻訳ありがとうございます！レビューの前に、改行位置がずれているのを直してもらえますか？

2022-09-18 00:36 UTC, kasaharu commented
確認します！

2022-09-18 00:53 UTC, kasaharu commented
@lacolaco 修正したのでレビューお願いします！

2022-09-19 04:59 UTC, lacolaco requested changes
翻訳ありがとうございます！コメントした部分の修正をお願いします :bow:

2022-09-19 04:59 UTC, lacolaco commented on aio-ja/content/guide/change-detection-zone-pollution.md
> +スケジュールされた[タスク](https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide#tasks)や[マイクロタスク](https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide#microtasks)
```suggestion
スケジュールされた[タスク](https://developer.mozilla.org/ja/docs/Web/API/HTML_DOM_API/Microtask_guide#%E3%82%BF%E3%82%B9%E3%82%AF)や[マイクロタスク](https://developer.mozilla.org/ja/docs/Web/API/HTML_DOM_API/Microtask_guide#%E3%83%9E%E3%82%A4%E3%82%AF%E3%83%AD%E3%82%BF%E3%82%B9%E3%82%AF)がデータモデルに変更を加えないため、変更検知の実行が不要になるケースがあります。一般的な例としては、
```

2022-09-19 04:59 UTC, lacolaco commented on aio-ja/content/guide/change-detection-zone-pollution.md
> +Angular DevTools を使用すると、不要な変更検知の呼び出しを見つけることができます。多くの場合、それらはプロファイラのタイムライン上に、source `setTimeout`、`setInterval`、`requestAnimationFrame`、またはイベントハンドラーの連続したバーとして表示されます。
```suggestion
Angular DevTools を使用すると、不要な変更検知の呼び出しを見つけることができます。多くの場合、それらはプロファイラのタイムライン上に、呼び出し元の `setTimeout`、`setInterval`、`requestAnimationFrame`、またはイベントハンドラーの連続したバーとして表示されます。
```

2022-09-19 04:59 UTC, lacolaco commented on aio-ja/content/guide/change-detection-zone-pollution.md
> +このような場合、[NgZone](https://angular.io/guide/zone) を使って指定されたコードによってスケジュールされたタスクの変更検知を呼び出さないよう Angular に指示することができます。
```suggestion
このような場合、[NgZone](https://angular.io/guide/zone) を使って、特定のコードによってスケジュールされたタスクの変更検知を呼び出さないよう Angular に指示することができます。
```

2022-09-19 04:59 UTC, lacolaco commented on aio-ja/content/guide/change-detection-zone-pollution.md
> +`RunOutsideAngular` 内で `Plotly.newPlot('chart', data);` を実行すると、初期化ロジックによってスケジュールされたタスクの実行後に変更検知を実行しないようフレームワークに指示します。
```suggestion
`runOutsideAngular` 内で `Plotly.newPlot('chart', data);` を実行すると、初期化ロジックによってスケジュールされたタスクの実行後に変更検知を実行しないようフレームワークに指示します。
```

2022-09-21 00:11 UTC, kasaharu commented on aio-ja/content/guide/change-detection-zone-pollution.md
> +スケジュールされた[タスク](https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide#tasks)や[マイクロタスク](https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide#microtasks)
なるほど、リンク先も日本語ページがあればそちらを参照するんですね！

2022-09-21 00:12 UTC, kasaharu commented
@lacolaco ありがとうございます！suggestion をそのまま取り込む形で対応しました！

2022-09-21 09:55 UTC, lacolaco approved these changes

2022-09-21 09:55 UTC, merged