translate: guide/standalone-components
angular/angular-ja pull request #784
Opened 2022-09-25 17:18 UTC by komura-c

## 翻訳・修正

- [x] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/main/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue

#768

### 備考
よろしくお願いします！

2022-10-07 09:38 UTC, lacolaco commented
@komura-c 

> 翻訳し終わった後に気づいたのですが、本家の方が更新されているっぽいです

本家のほうの原文を `.en.md` ファイルに上書きして、それをもとに翻訳をしていただけるのが一番ですが、現状の翻訳でいったんmergeしておいて、次のorigin同期のタイミングで差分が小さければメンテナのほうで追従しておくこともできます。どちらでもかまいません

2022-10-10 15:13 UTC, komura-c commented
> 本家のほうの原文を .en.md ファイルに上書きして、それをもとに翻訳

こちらで対応しました、お手隙でご確認お願いします！

変更箇所 (https://togithub.com/angular/angular/blob/main/aio/content/guide/standalone-components.md)
- developer previewへのリンク
- In v14 and higher, ... のセクションの移動
- iframeタグ
- ### Lazy loading and default exports セクションの追加
- export CAROUSEL_DIRECTIVES にconst追加

2022-10-13 12:33 UTC, lacolaco requested changes
翻訳ありがとうございます！コメントした部分の修正をお願いします :bow:
機械翻訳を利用することは問題ありませんが、表記ゆれや翻訳残りなど事前にセルフレビューを忘れないようにお願いします 🙏

2022-10-13 12:33 UTC, lacolaco commented on aio-ja/content/guide/standalone-components.md
> +v14以降では、 **スタンドアロンコンポーネント** は Angular アプリケーションを構築するための簡略化された方法を提供します。スタンドアロンコンポーネント、ディレクティブ、パイプは、 `NgModule`s の必要性を減らすことでオーサリングエクスペリエンスを効率化することを目的としています。既存のアプリケーションは、破壊的な変更を行うことなく、新しいスタンドアロンスタイルをオプショ
```suggestion
v14以降では、 **スタンドアロンコンポーネント** は Angular アプリケーションを構築するための簡略化された方法を提供します。スタンドアロンコンポーネント、ディレクティブ、パイプは、 `NgModule` の必要性を減らすことでオーサリングエクスペリエンスを効率化することを目的としています。既存のアプリケーションは、破壊的な変更を行うことなく、新しいスタンドアロンスタイルをオプションで段階的に採用できます。
```

2022-10-13 12:33 UTC, lacolaco commented on aio-ja/content/guide/standalone-components.md
> +アプリケーションをブートストラップするとき、 Angular の依存性の注入を構成し、アプリケーション全体で使用する構成値またはサービスを提供したいことがよくあります。 これらをプロバイダーとして  `bootstrapApplication` に渡すことができます:
```suggestion
アプリケーションをブートストラップするとき、 Angular の依存性の注入を構成し、アプリケーション全体で使用する設定値やサービスを提供したいことがよくあります。 これらをプロバイダーとして  `bootstrapApplication` に渡すことができます:
```

2022-10-13 12:33 UTC, lacolaco commented on aio-ja/content/guide/standalone-components.md
> +スタンドアロンのブートストラップオペレーションは、依存性の注入のために `Provider` のリストを明示的に構成することに基づいています。 ただし、既存のライブラリは、DI を構成するために `NgModule`s に依存している場合があります。たとえば、Angular のルーターは  `RouterModule.forRoot()` ヘルパーを使用して、アプリケーションでルーティングをセッ
```suggestion
スタンドアロンのブートストラップオペレーションは、依存性の注入のために `Provider` のリストを明示的に構成することに基づいています。 ただし、既存のライブラリは、DI を構成するために `NgModule` に依存している場合があります。たとえば、Angular のルーターは  `RouterModule.forRoot()` ヘルパーを使用して、アプリケーションでルーティングをセットアップします。 `importProvidersFrom` ユーティリティを介して `bootstrapApplication` でこれらの既存の `NgModule` を使用できます:
```

2022-10-13 12:33 UTC, lacolaco commented on aio-ja/content/guide/standalone-components.md
> +      RouterModule.forRoot([/* アプリケーションルート */]),
```suggestion
      RouterModule.forRoot([/* ルーティング設定 */]),
```

意訳ですがこちらのほうが意味が伝わると思いました

2022-10-13 12:33 UTC, lacolaco commented on aio-ja/content/guide/standalone-components.md
> +### 一度に多くのルートを遅延ロードする
```suggestion
### 一度に多くのルートを遅延読み込みする
```

2022-10-13 12:33 UTC, lacolaco commented on aio-ja/content/guide/standalone-components.md
> +`loadChildren` オペレーションは、ルートを宣言するために `RouterModule.forChild` をインポートして遅延ロードする `NgModule` を記述しなくても、子 `Route` の新しいセットのロードをサポートするようになりました。 これは、この方法でロードされたすべてのルートがスタンドアロンコンポーネントを使用している場合に機能します。
```suggestion
`loadChildren` オペレーションは、ルートを宣言するために `RouterModule.forChild` をインポートして遅延読み込みする `NgModule` を記述しなくても、子 `Route` の新しいセットの読み込みをサポートするようになりました。 これは、この方法で読み込まれたすべてのルートがスタンドアロンコンポーネントを使用している場合に機能します。
```

2022-10-13 12:33 UTC, lacolaco commented on aio-ja/content/guide/standalone-components.md
> +`NgModule`s (`loadChildren`) の遅延ロード API は、ルートの遅延ロードされた子をロードするときに、新しい「モジュール」インジェクターを作成します。この機能は、アプリケーション内のルートのサブセットにのみサービスを提供するのに役立つことがよくありました。 たとえば、 `/admin` の下のすべてのルートが `loadChildren` 境界を使用して範囲指定されて
```suggestion
`NgModule` (`loadChildren`) の遅延読み込み API は、ルートの遅延読み込みされた子を読み込むときに、新しい「モジュール」インジェクターを作成します。この機能は、アプリケーション内のルートのサブセットにのみサービスを提供するのに役立つことがよくありました。 たとえば、 `/admin` の下のすべてのルートが `loadChildren` 境界を使用して範囲指定されている場合、管理者専用サービスはそれらのルートにのみ提供できます。問題のルートの遅延読み込みが不要であったとしても、これを行うには `loadChildren` API を使用する必要がありました。
```

2022-10-13 12:33 UTC, lacolaco commented on aio-ja/content/guide/standalone-components.md
> +ルーターは `Route` 上で追加の `providers` を明示的に指定することをサポートするようになり、遅延ロードや `NgModule` を使用せずに同じスコープを指定できるようになりました。たとえば、 `/admin` のルート構造でスコープされたサービスは、次のようになります:
```suggestion
ルーターは `Route` 上で追加の `providers` を明示的に指定することをサポートするようになり、遅延読み込みや `NgModule` を使用せずに同じスコープを指定できるようになりました。たとえば、 `/admin` のルート構造でスコープされたサービスは、次のようになります:
```

2022-10-13 12:33 UTC, lacolaco commented on aio-ja/content/guide/standalone-components.md
> +`providers` を追加のルーティング設定の `loadChildren` と組み合わせて、`NgModule` を追加のルートとルートレベルのプロバイダーで遅延ロードするのと同じ効果を達成することもできます。 この例では、上記と同じプロバイダー/子ルートを構成しますが、遅延ロードされた境界の背後にあります。
```suggestion
`providers` を追加のルーティング設定の `loadChildren` と組み合わせて、`NgModule` を追加のルートとルートレベルのプロバイダーで遅延読み込みするのと同じ効果を達成することもできます。 この例では、上記と同じプロバイダー/子ルートを構成しますが、遅延読み込みされた境界の背後にあります。
```

2022-10-13 12:33 UTC, lacolaco commented on aio-ja/content/guide/standalone-components.md
> +  // admin ルートを遅延ロード
```suggestion
  // admin ルートを遅延読み込み
```

2022-10-13 12:33 UTC, lacolaco commented on aio-ja/content/guide/standalone-components.md
> +スタンドアロンコンポーネント、ディレクティブ、およびパイプは、それらをインポートする NgModule からエクスポートできます:
```suggestion
スタンドアロンコンポーネント、ディレクティブ、およびパイプは、それらをインポートする `NgModule` からエクスポートできます:
```

2022-10-13 12:33 UTC, lacolaco commented on aio-ja/content/guide/standalone-components.md
> +`NgModule` を発行する代わりに、ライブラリの作成者は協調するディレクティブの配列をエクスポートしたいと思うかもしれません:
```suggestion
`NgModule` を公開する代わりに、ライブラリの作成者は協調するディレクティブの配列をエクスポートしたいと思うかもしれません:
```

2022-10-13 12:33 UTC, lacolaco commented on aio-ja/content/guide/standalone-components.md
> +このような配列は、 `NgModule`s を使用するアプリケーションによってインポートされ、 `@NgModule.imports` に追加されます。 TypeScript の `as const` コンストラクトの存在に注意してください。これは、適切なコンパイルに必要な追加情報を Angular コンパイラに提供し、推奨される方法です (これにより、エクスポートされた配列が TypeScri
```suggestion
このような配列は、 `NgModule` を使用するアプリケーションによってインポートされ、 `@NgModule.imports` に追加されます。 TypeScript の `as const` 構成の存在に注意してください。これは、適切なコンパイルに必要な追加情報を Angular コンパイラに提供し、推奨される方法です (これにより、エクスポートされた配列が TypeScript の観点からイミュータブルになるため)。
```

2022-10-13 12:33 UTC, lacolaco commented on aio-ja/content/guide/standalone-components.md
> +`NgModule`s をオプションにすると、アプリケーション全体のプロバイダー ([HttpClient](https://angular.io/api/common/http/HttpClient) など) を使用して「モジュール」インジェクターを構成する新しい方法が必要になります。スタンドアロンアプリケーション (`bootstrapApplication` で作成されたアプリケーション)
```suggestion
`NgModule` をオプショナルにすると、アプリケーション全体のプロバイダー ([HttpClient](https://angular.io/api/common/http/HttpClient) など) を使用して「モジュール」インジェクターを構成する新しい方法が必要になります。スタンドアロンアプリケーション (`bootstrapApplication` で作成されたアプリケーション) では、`providers` オプションで、ブートストラッププロセス中に「モジュール」プロバイダーを構成できます:
```

2022-10-13 12:33 UTC, lacolaco commented on aio-ja/content/guide/standalone-components.md
> +新しいブートストラップ API は、 `NgModule`s を使用せずに「モジュールインジェクター」を構成する手段を提供します。この意味で、名前の「モジュール」部分はもはや関連性がなく、新しい用語を導入することにしました: それが、「環境インジェクター」です。
```suggestion
新しいブートストラップ API は、 `NgModule` を使用せずに「モジュールインジェクター」を構成する手段を提供します。この意味で、名前の「モジュール」部分はもはや関連性がなく、新しい用語を導入することにしました: それが、「環境インジェクター」です。
```

2022-10-13 12:33 UTC, lacolaco commented on aio-ja/content/guide/standalone-components.md
> +Angular v14 では、この新しい命名を表す新しい TypeScript タイプ `EnvironmentInjector` が導入されています。付属の `createEnvironmentInjector` API を使用すると、環境インジェクターをプログラムで作成できます:
```suggestion
Angular v14 では、この新しい命名を表す新しい TypeScript の型 `EnvironmentInjector` が導入されています。付属の `createEnvironmentInjector` API を使用すると、環境インジェクターをプログラムで作成できます:
```

2022-10-16 09:13 UTC, komura-c commented
@lacolaco 
セルフレビューが足らずに申し訳ありませんでした🙇
さらに読み返した所、以下の点を修正しましたのでよろしくお願いします🙇
- [fix: レビュー内容を修正](https://github.com/angular/angular-ja/pull/784/commits/8e22a6bb07284c273ad91f6924d4884531bdc11d)
- [fix: :を。に修正](https://github.com/angular/angular-ja/pull/784/commits/dd7025b7b9c0215920e975febbc1a99980f3ecaa)
- [fix: まだ本家で公開されてない部分を削除、接続詞の微修正](https://github.com/angular/angular-ja/pull/784/commits/81b2df317a07c1b32bded197a478a013a7a2c52e)
→こちらの本家でまだ公開されてない部分を削除しました https://angular.io/guide/standalone-components

2022-10-16 09:14 UTC, komura-c commented on aio-ja/content/guide/standalone-components.md
> +`providers` を追加のルーティング設定の `loadChildren` と組み合わせて、`NgModule` を追加のルートとルートレベルのプロバイダーで遅延読み込みするのと同じ効果を達成することもできます。 この例では、上記と同じプロバイダー/子ルートを構成しますが、遅延読み込みされた境界の後ろにあります。
また、この部分が原文で理解できず良い翻訳ができませんでしたが、どう思いますか？

2022-10-19 00:48 UTC, lacolaco approved these changes
LGTMです！ありがとうございます！

2022-10-19 00:49 UTC, lacolaco commented on aio-ja/content/guide/standalone-components.md
> +`providers` を追加のルーティング設定の `loadChildren` と組み合わせて、`NgModule` を追加のルートとルートレベルのプロバイダーで遅延読み込みするのと同じ効果を達成することもできます。 この例では、上記と同じプロバイダー/子ルートを構成しますが、遅延読み込みされた境界の後ろにあります。
そもそも原文がややこしいので、ここはこのままで一旦大丈夫かと思います

2022-10-19 00:50 UTC, merged

2022-10-19 04:54 UTC, komura-c commented
ありがとうございました！🙏