translate: guide/change-detection-slow-computations
angular/angular-ja pull request #786
Opened 2022-10-02 08:51 UTC by kasaharu

## 翻訳・修正

- [x] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/main/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue

#760

### 備考

2022-10-07 11:46 UTC, lacolaco requested changes
翻訳ありがとうございます！コメントした部分の修正をお願いします :bow:

2022-10-07 11:46 UTC, lacolaco commented on aio-ja/content/guide/change-detection-slow-computations.md
> +- **ライフサイクルフックでの再描画/リフローの回避。**特定の[操作](https://web.dev/avoid-large-complex-layouts-and-layout-thrashing/)により、ブラウザはページのレイアウトを同期的に再計算するか、再レンダリングします。リフローと再描画は一般に低速なので、変更検知のたびに実行するのは避けたいです。
```suggestion
- **ライフサイクルフックでのリペイント/リフローの回避。**特定の[操作](https://web.dev/avoid-large-complex-layouts-and-layout-thrashing/)により、ブラウザはページのレイアウトを同期的に再計算するか、再レンダリングします。リフローとリペイントは一般に低速なので、変更検知のたびに実行するのは避けたいものです。
```

ブラウザのレンダリング用語なのでリフローとリペイントはカタカナにします

2022-10-07 11:46 UTC, lacolaco commented on aio-ja/content/guide/change-detection-slow-computations.md
> +純粋なパイプとメモ化ではトレードオフが異なります。純粋なパイプは Angular の組み込み概念で、関数の結果をキャッシュする一般的なソフトウェアエンジニアリングのプラクティスであるメモ化と比較すると、その差は歴然です。メモ化のメモリオーバーヘッドは、重い計算を異なる引数で頻繁に呼び出す場合、大きくなる可能性があります。
```suggestion
純粋なパイプとメモ化には異なるトレードオフがあります。関数の結果をキャッシュする一般的なソフトウェアエンジニアリングのプラクティスであるメモ化に対して、純粋なパイプは Angular の組み込みの概念です。重い計算を異なる引数で頻繁に呼び出すと、メモ化のメモリオーバーヘッドは大きくなる可能性があります。
```

2022-10-09 01:34 UTC, kasaharu commented
@lacolaco レビューありがとうございます！suggestion の内容を確認して取り込みました。

2022-10-09 01:57 UTC, lacolaco approved these changes
修正ありがとうございます！

2022-10-09 01:57 UTC, merged