translate: guide/change-detection-skipping-subtrees
angular/angular-ja pull request #790
Opened 2022-10-12 03:13 UTC by 2YY

## 翻訳・修正

- [x] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/main/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue

#761

### 備考

- 原文L14: `〜な場合` という言い回しでL13と言い回しを揃えた方が自然かと思い、言葉の順番入れ替え的な意訳が入っております。

2022-10-16 01:44 UTC, lacolaco requested changes
翻訳ありがとうございます！コメントした部分の修正をお願いします :bow:

2022-10-16 01:44 UTC, lacolaco commented on aio-ja/content/guide/change-detection-skipping-subtrees.md
> +Angular が `OnPush` 戦略なしでコンポーネント内のイベントを処理する場合、フレームワークはコンポーネントツリー全体で変更検知を実行します。 Angular は、新しい入力を受け取っていない `OnPush` を使用して、ルートをもつ子孫コンポーネントサブツリーをスキップします。
```suggestion
Angular が `OnPush` 戦略なしでコンポーネント内のイベントを処理する場合、フレームワークはコンポーネントツリー全体で変更検知を実行します。 Angular は、`OnPush` を使用し、新しい入力を受け取っていない親を持つ子孫コンポーネントサブツリーをスキップします。
```

意訳が入ってますが、句の修飾のかかり方はこういう感じかと思います

2022-10-16 01:44 UTC, lacolaco commented on aio-ja/content/guide/change-detection-skipping-subtrees.md
> +* **TypeScript コードの入力プロパティを変更する場合**。 `@ViewChild` や `@ContentChild` などの API を使用して TypeScript のコンポーネントへの参照を取得し、`@Input` プロパティを手動で変更すると、Angular は OnPush コンポーネントの変更検知を自動的に実行しません。 Angular で変更検知を実行する必要がある
```suggestion
* **TypeScript コード中で入力プロパティを変更する場合**。 `@ViewChild` や `@ContentChild` などの API を使用して TypeScript 中でコンポーネントへの参照を取得し、`@Input` プロパティを手動で変更すると、Angular は OnPush コンポーネントの変更検知を自動的に実行しません。 Angular で変更検知を実行する必要がある場合は、コンポーネントに `ChangeDetectorRef` を注入し、`changeDetectorRef.markForCheck()` を呼び出すことで、変更検知をスケジュールするように Angular に指示できます。
```

2022-10-17 03:19 UTC, 2YY commented
レビュー頂き有難うございます、指摘頂いた箇所の修正いたしました！

2022-10-17 15:04 UTC, 2YY commented
チェック漏れておりました、Push しました！

2022-10-19 00:51 UTC, lacolaco approved these changes
LGTMです！

2022-10-19 00:52 UTC, merged