translate: guide/class-binding
angular/angular-ja pull request #799
Opened 2022-12-03 21:13 UTC by IRod22

## 翻訳・修正

- [x] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/main/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue

#749

### 備考
- `yarn` が `.yarn` フォルダーを追加したため、`.gitignore` ファイルを変更する必要がありました。これは `node_modules` に似ています。
- 57 行目と 61 行目のセマンティクスを維持しようとしました。 Google 翻訳が「dash-case」を「ダッシュケース」と間違えました。

2022-12-04 14:22 UTC, IRod22 commented
@lacolaco、先に進んで、次の週まで変更を実装できないかもしれないと伝えたいと思います。また、日本のこのコミュニティに貢献させてくれてありがとう。個人的なメモでは、私は数ヶ月間[活動家](https://medium.com/@ivan18rod)であり、私たち全員が人間であり、私たちが1つとして協力する必要があると主張しようとしています。正直に言うと、私はこのコミュニティが以前にそれを見て受け入れるほど大きなコミュニティを見ていません。

2022-12-07 03:36 UTC, IRod22 commented
[この失敗した実行](https://github.com/angular/angular-ja/actions/runs/3610264497/jobs/6134540924) は #798 に関連している可能性があります。

2022-12-07 04:54 UTC, lacolaco requested changes
翻訳ありがとうございます！コメントした部分の修正をお願いします :bow:

また、 #798 の問題は残っていますが、翻訳のコミットにpackage.jsonやyarn.lockなどの差分が混入すべきではありません。Markdownファイルの変更だけを含んだコミットに修正してもらえますか？

2022-12-07 04:54 UTC, lacolaco commented on aio-ja/content/guide/class-binding.md
> +クラスおよびスタイル バインディングを使用して、要素の `class` 属性から CSS クラス名を追加および削除し、スタイルを動的に設定します。
```suggestion
クラスおよびスタイルバインディングを使用して、要素の `class` 属性から CSS クラス名を追加および削除し、スタイルを動的に設定します。
```

2022-12-07 04:54 UTC, lacolaco commented on aio-ja/content/guide/class-binding.md
> +単一のクラス バインディングを作成するには、次のように入力します:
```suggestion
単一のクラスバインディングを作成するには、次のように入力します:
```

2022-12-07 04:54 UTC, lacolaco commented on aio-ja/content/guide/class-binding.md
> +`object`、`Array`、`Map`、`Set` などのオブジェクトのような式では、Angular がクラス リストを更新するために、オブジェクトの ID を変更する必要があります。
```suggestion
`object`、`Array`、`Map`、`Set` などのオブジェクトのような式では、Angular がクラスリストを更新するために、オブジェクトの ID を変更する必要があります。
```

2022-12-07 04:54 UTC, lacolaco commented on aio-ja/content/guide/class-binding.md
> +次の表は、クラス バインディングの構文をまとめたものです。
```suggestion
次の表は、クラスバインディングの構文をまとめたものです。
```

2022-12-07 04:54 UTC, lacolaco commented on aio-ja/content/guide/class-binding.md
> +| 製本タイプ         | 構文                      | 入力方式                                                                  | 入力値の例 |
```suggestion
| バインディング形式         | 構文                      | 入力方式                                                                  | 入力値の例 |
```

2022-12-07 04:54 UTC, lacolaco commented on aio-ja/content/guide/class-binding.md
> +| マルチクラス バインディング  | `[class]="classExpression"` | <code>Array&lt;string&gt;</code>                                            | `['foo', 'bar']`                     |
```suggestion
| マルチクラスバインディング  | `[class]="classExpression"` | <code>Array&lt;string&gt;</code>                                            | `['foo', 'bar']`                     |
```

2022-12-07 04:54 UTC, lacolaco commented on aio-ja/content/guide/class-binding.md
> +単一のスタイル バインディングを作成するには、プレフィックス `style` の後にドットと CSS スタイルの名前を付けて使用します。
```suggestion
単一のスタイルバインディングを作成するには、プレフィックス `style` の後にドットと CSS スタイルの名前を付けて使用します。
```

2022-12-07 05:33 UTC, IRod22 commented
@lacolaco、package.jsonを元に戻しましたが、npmのpackage-lock.jsonのようなyarn.lockを元に戻すことはできず、必要な依存関係をインストールしたときに更新されました。明日修正を探しますが、もう寝ます。 私にとってはほぼ真夜中です... :yawning_face:

2022-12-07 14:19 UTC, IRod22 commented
@lacolaco

ソフトウェアの整合性とソフトウェアのセキュリティに関する私の知識、以前のコメント、および以下にリンクされている参考文献を踏まえると、セキュリティと整合性の理由から、yarn.lock を元に戻すことはお勧めしません。確かに、それでも元に戻したいのであれば、あなたや他の翻訳者がロックファイルの更新をどのように防いだかを知る必要があります。 ただし、これらの更新は**大きな**理由で必要です。Yarn は実際にチェックサムを使用して、正しいバージョンの正しいパッケージをインストールしていることを確認します。 Yarn は整合性エラーを出力します。チェックサムが一致しない場合、開発者は問題のパッケージを探してアンインストールし、再インストールする必要があるため、インストール プロセスが遅くなります。

より適切で安全な解決策は、Dependabot に依存関係を処理させることです。したがって、yarn.lock を自分で変更する必要はありません。

---

## 参考文献
- https://www.arahansen.com/the-ultimate-guide-to-yarn-lock-lockfiles/ ([翻訳済み](https://www-arahansen-com.translate.goog/the-ultimate-guide-to-yarn-lock-lockfiles/?_x_tr_sl=en&_x_tr_tl=ja&_x_tr_hl=en&_x_tr_pto=wapp))
- https://classic.yarnpkg.com/lang/en/docs/yarn-lock/ ([翻訳済み](https://classic-yarnpkg-com.translate.goog/lang/en/docs/yarn-lock/?_x_tr_sl=en&_x_tr_tl=ja&_x_tr_hl=en&_x_tr_pto=wapp))
- https://www.howtogeek.com/363735/what-is-a-checksum-and-why-should-you-care/ ([翻訳済み](https://www-howtogeek-com.translate.goog/363735/what-is-a-checksum-and-why-should-you-care/?_x_tr_sl=en&_x_tr_tl=ja&_x_tr_hl=en&_x_tr_pto=wapp))

2022-12-07 15:23 UTC, lacolaco commented
@IRod22 This repository requires Yarn v1. Other versions of Yarn are incompatible. Please avoid including changes that are not related to translation.

2022-12-08 01:13 UTC, IRod22 commented
@lacolaco、`angular:main` をフォークしたときに yarn.lock を元に戻すことができたので、以前のコメントは無視してかまいません。依存関係をインストールした後、ターミナルで最新のコミット ID を使用して以下のコマンドを実行するように、他の新規参入者に通知する必要があることに注意してください。

```bash
$ git checkout [COMMIT ID] -- yarn.lock
```

ところで、先程は申し訳ありませんでした; また、起こしてしまったらごめんなさい…

2022-12-08 22:52 UTC, IRod22 commented
おはよう@lacolaco; すべてが準備完了です。変更内容を確認してマージする前に、いくつか質問させてください。
1. ディスカッションのロックを解除してもよろしいですか? [Q&A で助けを求めることができるとおっしゃいましたが](https://github.com/angular/angular-ja/issues/749#issuecomment-1336002467)、新しいディスカッションを開く方法がありません。 ディスカッションのロックを解除することは、他の翻訳者にも利益をもたらします。
2. ディスカッションのロックを解除できない場合は、CONTRIBUTING.md を編集して、[現在のセットアップ ワークフロー](https://github.com/angular/angular-ja/issues/749#issuecomment-1336199428)を私が見つけたワークフローに置き換えていただけますか?

それ以外では、貢献させていただきありがとうございます。#692 を翻訳する準備ができていると思います。

2022-12-10 22:54 UTC, IRod22 commented on aio-ja/content/guide/class-binding.md
> +## 次のお勧め
@lacolaco、先に進んで変更を実装しました[textlintが推奨](https://github.com/angular/angular-ja/actions/runs/3652635602/jobs/6194504422)。

2022-12-11 03:11 UTC, lacolaco approved these changes

2022-12-11 03:11 UTC, merged

2022-12-11 03:12 UTC, lacolaco commented
翻訳ありがとうございました！