[wip] translate: guide/angular-package-format
angular/angular-ja pull request #802
Opened 2022-12-16 16:45 UTC by IRod22

## 翻訳・修正

- [ ] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/main/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue

#692

### 備考

- これは進行中の作業です。 これは翻訳中の大きなファイルなので、コミットごとにいくつかのセクションを翻訳しています。
-

2022-12-18 02:52 UTC, IRod22 commented
@lacolaco さん、このプル リクエストはレビューの準備ができています。 確認事項が多いので最新の備考欄をご覧ください。

2022-12-18 14:54 UTC, IRod22 commented on aio-ja/content/guide/angular-package-format.md
> +詳細: [副作用に関する webpack ドキュメント](https://github.com/webpack/webpack/tree/master/examples/side-effects)
In Solidarity からのこの通知は URL に記載されているため、無視してください。

2022-12-19 22:23 UTC, IRod22 commented
@lacolaco プレッシャーはありませんが、これを見直してもよろしいですか？ 今週いっぱい忙しいので、明日エラーを修正したいと思います。

2023-01-21 02:39 UTC, lacolaco requested changes
翻訳ありがとうございます！ コメントした部分の修正をお願いします

単語の中に空白を含めないようにしてください。これに関してすべての場所を指摘できていないかもしれません。

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +Angular コンパイラは、インデックス ES モジュール ファイルを生成できます。 Rollup などのツールは、これらのファイルを使用して、フラット化されたモジュールを *Flattened ES Module* (FESM) ファイル形式で生成できます。
```suggestion
Angular コンパイラは、インデックス ES モジュールファイルを生成できます。 Rollup などのツールは、これらのファイルを使用して、フラット化されたモジュールを *Flattened ES Module* (FESM) ファイル形式で生成できます。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +これは、パッケージからのすべてのインポートをたどり、そのコードを単一のファイルにコピーすることによって形成されますが、すべてのパブリック ES エクスポートを保持し、すべてのプライベート インポートを削除します。
```suggestion
これは、パッケージからのすべてのインポートをたどり、そのコードを単一のファイルにコピーすることによって形成されますが、すべてのパブリック ES エクスポートを保持し、すべてのプライベートインポートを削除します。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +したがって、FESM5 ファイルは ESM+ES5 になり、インポート/エクスポート ステートメントと ES5 ソース コードが含まれます。
```suggestion
したがって、FESM5 ファイルは ESM+ES5 になり、インポート/エクスポート文と ES5 のソースコードが含まれます。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +フラット化された ES Module インデックス ファイルを生成するには、tsconfig.json ファイルで次の構成オプションを使用します。
```suggestion
フラット化された ES Module インデックスファイルを生成するには、tsconfig.json ファイルで次の構成オプションを使用します。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +この問題は調査中です。 サイズ回帰の問題が解決された後、「module」および「es2020」package.json エントリ ポイントをフラット化されていないファイルに切り替えることが期待されています。
```suggestion
この問題は調査中です。 サイズ回帰の問題が解決された後、`module`および`es2020`のpackage.json エントリポイントをフラット化されていないファイルに切り替えることが期待されています。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +これらのシンボルがインポートおよび使用されていない場合は、ツリー シェイキングと呼ばれる最適化プロセスでそれらを削除することが望ましいことが多く、副作用のあるコードによってこれを防ぐことができます。
```suggestion
これらのシンボルがインポートおよび使用されていない場合は、ツリーシェイキングと呼ばれる最適化プロセスでそれらを削除することが望ましいことが多く、副作用のあるコードによってこれを防ぐことができます。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +Webpack などのビルド ツールは、モジュールの最上位レベルで副作用のあるコードに依存しないことをパッケージが宣言できるようにするフラグをサポートし、ツールがパッケージからコードをツリーシェイクする自由度を高めます。
```suggestion
Webpack などのビルドツールは、モジュールの最上位レベルで副作用のあるコードに依存しないことをパッケージが宣言できるようにするフラグをサポートし、ツールがパッケージからコードをツリーシェイクする自由度を高めます。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +これらの最適化の最終結果は、バンドル サイズが小さくなり、コード分割後のバンドル チャンクでのコード分散が改善されるはずです。
```suggestion
これらの最適化の最終結果は、バンドルサイズが小さくなり、コード分割後のバンドルチャンクでのコード分散が改善されるはずです。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +以前の APF バージョンでは、各エントリ ポイントには .d.ts エントリ ポイントの隣に「src」ディレクトリがあり、このディレクトリには元のソース コードの構造に一致する個々の d.ts ファイルが含まれていました。
```suggestion
以前の APF バージョンでは、各エントリポイントには .d.ts エントリ ポイントの隣に `src` ディレクトリがあり、このディレクトリには元のソースコードの構造に一致する個々の d.ts ファイルが含まれていました。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +APF v10 では、プライマリ エントリ ポイントの直接の依存関係として tslib を追加することをお勧めします。
```suggestion
APF v10 では、プライマリエントリポイントの直接の依存関係として tslib を追加することをお勧めします。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +このパッケージには、package.json と呼ばれるマニフェスト、コンパイルされたソース コード、typescript 定義ファイル、ソース マップ、メタデータなどが含まれます。
```suggestion
このパッケージには、package.json と呼ばれるマニフェスト、コンパイルされたソースコード、typescript 定義ファイル、ソース マップ、メタデータなどが含まれます。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +モジュールに含まれるクラス、関数、定数、または変数であり、オプションでモジュール エクスポートを介して外部の世界に表示されます。
```suggestion
モジュールに含まれるクラス、関数、定数、または変数であり、オプションでモジュールエクスポートを介して外部の世界に表示されます。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +シンボルをインポートおよびエクスポートするステートメントを含むファイル。
```suggestion
シンボルをインポートおよびエクスポートする文を含むファイル。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +Flattened ES Modules の略で、エントリ ポイントからアクセスできるすべての ES Module を 1 つの ES Module にフラット化することによって作成されたファイル形式で構成されます。
```suggestion
Flattened ES Modules の略で、エントリポイントからアクセスできるすべての ES Module を 1 つの ES Module にフラット化することによって作成されたファイル形式で構成されます。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +ビルド ツール \([Webpack](https://webpack.js.org) や [Rollup](https://rollupjs.org) など\) によって生成される単一の JS ファイルの形式のアーティファクトで、1 つ以上のモジュールに由来するシンボルが含まれています。
```suggestion
ビルドツール \([Webpack](https://webpack.js.org) や [Rollup](https://rollupjs.org) など\) によって生成される単一の JS ファイルの形式のアーティファクトで、1 つ以上のモジュールに由来するシンボルが含まれています。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +どちらのエントリ ポイントも `@angular/core` パッケージに存在しますが、異なるシンボルをエクスポートします。
```suggestion
どちらのエントリポイントも `@angular/core` パッケージに存在しますが、異なるシンボルをエクスポートします。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +パッケージには、多数のエントリ ポイントを含めることができます。
```suggestion
パッケージには、多数のエントリポイントを含めることができます。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +エントリ ポイントではないモジュールからシンボルを取得するプロセス。
```suggestion
エントリポイントではないモジュールからシンボルを取得するプロセス。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +エントリ ポイントからのインポート。
```suggestion
エントリポイントからのインポート。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +アプリケーションで使用されていないコードを特定して削除するプロセス。デッド コードの削除とも呼ばれます。
```suggestion
アプリケーションで使用されていないコードを特定して削除するプロセス。デッドコードの削除とも呼ばれます。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +これは、[Rollup](https://rollupjs.org)、[Closure Compiler](https://developers.google.com/closure/compiler)、または [Terser](https://github.com/terser/terser) などのツールを使用してアプリケーション レベルで実行されるグローバルな最適化です。
```suggestion
これは、[Rollup](https://rollupjs.org)、[Closure Compiler](https://developers.google.com/closure/compiler)、または [Terser](https://github.com/terser/terser) などのツールを使用してアプリケーションレベルで実行されるグローバルな最適化です。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +これは、特定の Angular ランタイム バージョンに関連付けられていないコンパイル済み Angular コードを生成する `ngc` のコンパイル モードです。アプリケーションに使用される完全なコンパイルとは対照的に、Angular コンパイラとランタイム バージョンが正確に一致する必要があります。
```suggestion
これは、特定の Angular ランタイムバージョンに関連付けられていないコンパイル済み Angular コードを生成する `ngc` のコンパイルモードです。アプリケーションに使用される完全なコンパイルとは対照的に、Angular コンパイラとランタイムバージョンが正確に一致する必要があります。
```

2023-01-21 02:39 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +    最新のビルド ツールの多くは、ES モジュール レベルでの「コード分割」\(遅延読み込みとも呼ばれます) のみが可能です。
```suggestion
    最新のビルドツールの多くは、ES モジュールレベルでの「コード分割」\(遅延読み込みとも呼ばれます) のみが可能です。
```

2023-01-21 23:47 UTC, IRod22 commented
@lacolaco、私はあなたの要求された変更をコミットしました。以下の正規表現をエディターの検索と置換機能に貼り付けることで、可能なすべての空白を見つけて置き換えましたが、単語間の空白を見逃した可能性があります。

```
([一-龠]+|[ぁ-ゔ]+|[ァ-ヴー]+|[々〆〤ヶ]+)((\]\((https?:\/\/[\w\d.\/?=#]+)\))|\\?\))*\s+(\[|\\?\()*([一-龠]+|[ぁ-ゔ]+|[ァ-ヴー]+|[々〆〤ヶ]+)
```
*(このパターンは、https://regexr.com/ でコピーしてデバッグできます。)*

また、Textlint の[推奨事項](https://github.com/angular/angular-ja/actions/runs/3976953761/jobs/6817754743#step:5:13)に従ってくださいますか?

2023-01-22 00:59 UTC, lacolaco commented
@IRod22 Sorry, I can't understand what you're saying. You should execute `textlint --fix` to fix lint errors.

2023-01-22 01:54 UTC, IRod22 commented
@lacolaco, it looks like 3 out of 6 PR checks have practically failed, including the `build-and-test / build-ubuntu` run (`build-and-test / build-macos` may have "hung" because it is taking longer than the other two runners). Does the workflow to publish to `angular.jp` run on `ubuntu-latest`? If so, the build process might not work after you merge my changes.

2023-01-22 02:23 UTC, lacolaco commented
@IRod22 Yes, ubuntu-latest should always be green. And "Dangling links" errors are needed to be fixed before merged.

2023-01-22 04:00 UTC, IRod22 commented
Fixed!

2023-01-22 07:43 UTC, lacolaco requested changes
Thanks. Please fix a broken sentence.

2023-01-22 07:43 UTC, lacolaco commented on aio-ja/content/guide/angular-package-format.md
> +部分的にコンパイルされたは、アライブラリコードプリケーションのビルドプロセス中に Angular CLI によって完全にコンパイルされたコードに変換されます。
```suggestion
部分的にコンパイルされたライブラリコードは、アプリケーションのビルドプロセス中に Angular CLI によって完全にコンパイルされたコードに変換されます。
```

2023-01-23 13:19 UTC, lacolaco approved these changes

2023-01-23 13:23 UTC, lacolaco commented
Thanks!

2023-01-23 13:54 UTC, merged