translate: guide/binding-overview (#747)
angular/angular-ja pull request #810
Opened 2023-01-18 22:27 UTC by ver-1000000

## 翻訳・修正

- [x] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/main/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue

#747 

### 備考
https://github.com/angular/angular-ja/blob/main/CONTRIBUTING.md#%E7%AE%87%E6%9D%A1%E6%9B%B8%E3%81%8D%E3%81%A7%E3%81%AE%E5%8F%A5%E7%82%B9%E3%81%AE%E6%9C%89%E7%84%A1%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6 によると、30行目(`|`や`&`などのビット演算子はサポートされない)については句点をつけるべきような気がしましたが、他のリストとの並びを顧みて句点をつけていません。

2023-01-20 23:50 UTC, lacolaco requested changes
翻訳ありがとうございます！コメントした部分の修正をお願いします :bow:

2023-01-20 23:50 UTC, lacolaco commented on aio-ja/content/guide/binding-overview.md
> +たとえば、バインディングは次を含みます:
```suggestion
次のものがバインディングの例に挙げられます:
```
ちょっと意訳ですが

2023-01-20 23:50 UTC, lacolaco commented on aio-ja/content/guide/binding-overview.md
> +* 文字補間
```suggestion
* 文字列補間
```

2023-01-20 23:50 UTC, lacolaco commented on aio-ja/content/guide/binding-overview.md
> +## シンタックス
```suggestion
## 構文
```

2023-01-20 23:50 UTC, lacolaco commented on aio-ja/content/guide/binding-overview.md
> +補間式にはコンテキストがあります&mdash;その式が属するアプリケーションの特定の部分。一般的に、このコンテキストはコンポーネントのインスタンスです。
```suggestion
補間式にはコンテキストがあります&mdash;それはその式が属するアプリケーションの特定の部分です。一般的に、このコンテキストはコンポーネントのインスタンスです。
```

2023-01-20 23:50 UTC, lacolaco commented on aio-ja/content/guide/binding-overview.md
> +テンプレート式は`undefined`を除き、グローバル名前空間からは何も参照することができません。また、`window`や`document`を参照することもできません。そして、`console.log()`や`Math.max()`を直接呼び出すこともできず、式コンテキストのメンバの参照に制限されます。
```suggestion
テンプレート式は`undefined`を除き、グローバル名前空間からは何も参照することができません。また、`window`や`document`を参照することもできません。そして、`console.log()`や`Math.max()`を直接呼び出すこともできず、式コンテキストのメンバー変数の参照に制限されます。
```

2023-01-20 23:50 UTC, lacolaco commented on aio-ja/content/guide/binding-overview.md
> +1. コンポーネントのメンバー名
```suggestion
1. コンポーネントのメンバー変数名
```

2023-01-20 23:50 UTC, lacolaco commented on aio-ja/content/guide/binding-overview.md
> +1. ディレクティブのコンテキスト名
```suggestion
1. ディレクティブのコンテキスト中の名前
```

2023-01-20 23:50 UTC, lacolaco commented on aio-ja/content/guide/binding-overview.md
> +変数が別のコンテキストでシャドウイングになる(意図が不明確になる)のを避けるため、変数名は一意に保つようにします。
```suggestion
変数が別のコンテキストの変数をシャドーイング（隠蔽する）のを避けるため、変数名は一意に保つようにします。
```

2023-01-25 02:27 UTC, ver-1000000 commented on aio-ja/content/guide/binding-overview.md
> +テンプレート式は`undefined`を除き、グローバル名前空間からは何も参照することができません。また、`window`や`document`を参照することもできません。そして、`console.log()`や`Math.max()`を直接呼び出すこともできず、式コンテキストのメンバの参照に制限されます。
58行目で`メンバ変数`という言葉を使っていたので、こちらも`メンバー変数`とします。

2023-01-25 02:34 UTC, ver-1000000 commented on aio-ja/content/guide/binding-overview.md
> +変数が別のコンテキストでシャドウイングになる(意図が不明確になる)のを避けるため、変数名は一意に保つようにします。
一つの文の中で補足の中括弧を利用する際は、
中括弧を外した状態でも文章として成立するべきだと思う(私はそういうものだと思っているのですが、本当？ 出典ナシ)ので、
`シャドーイングする(隠蔽する)のを`とします。

また、カッコは半角で統一します。

2023-01-25 03:12 UTC, lacolaco approved these changes
LGTM!

2023-01-25 03:14 UTC, merged