translate: guide/attribute-binding
angular/angular-ja pull request #818
Opened 2023-01-29 07:35 UTC by sugar-cat7

## 翻訳・修正

- [x] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/main/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue
#748 

### 備考

2023-01-29 07:52 UTC, sugar-cat7 commented
CLA登録したので、お手数ですがRerunしていただいてもよろしいでしょうか？

2023-01-29 07:55 UTC, lacolaco commented
@sugar-cat7 CLAの状態の更新のために cla/google の Detailsから、インストラクションの最後の new contributor 向けのリンクをクリックしてください
<img width="697" alt="image" src="https://user-images.githubusercontent.com/1529180/215313102-7ada68ea-d8d9-4fa9-870e-43fbe8376f5a.png">

2023-01-29 08:31 UTC, sugar-cat7 commented
@lacolaco 
状態更新しました。レビューお願いいたします！

2023-01-31 10:34 UTC, lacolaco requested changes
翻訳ありがとうございます！コメントした部分の修正をお願いします :bow:

2023-01-31 10:34 UTC, lacolaco commented on aio-ja/content/guide/attribute-binding.md
> +Angular での属性バインディングは、属性に直接値を設定するのに役立ちます。属性バインディングを使用することで、アクセシビリティの改善や、アプリケーションのスタイルを動的に変更し、複数の CSS クラスやスタイルを同時に管理することができます。
改行数を揃えていただきたいです

2023-01-31 10:34 UTC, lacolaco commented on aio-ja/content/guide/attribute-binding.md
> +2. `[attr.colspan]`に式を設定します。
原文では `1.` ですね
```suggestion
1. `[attr.colspan]`に式を設定します。
```

2023-01-31 10:34 UTC, lacolaco commented on aio-ja/content/guide/attribute-binding.md
ここも原文と改行の数がずれてそうです（空行がはいってしまっている）

2023-01-31 14:35 UTC, sugar-cat7 commented on aio-ja/content/guide/attribute-binding.md
> +Angular での属性バインディングは、属性に直接値を設定するのに役立ちます。属性バインディングを使用することで、アクセシビリティの改善や、アプリケーションのスタイルを動的に変更し、複数の CSS クラスやスタイルを同時に管理することができます。
改行数揃えました。
https://github.com/angular/angular-ja/pull/818/commits/2cc34357f2e938942a5a54400c21258749768e35

2023-01-31 14:36 UTC, sugar-cat7 commented on aio-ja/content/guide/attribute-binding.md
空行削除しました。
https://github.com/angular/angular-ja/pull/818/commits/2cc34357f2e938942a5a54400c21258749768e35

2023-02-04 11:59 UTC, lacolaco approved these changes
修正ありがとうございました！

2023-02-04 15:30 UTC, merged