translate i18n
angular/angular-ja pull request #838
Opened 2023-04-23 15:35 UTC by IRod22

## 翻訳・修正

- [x] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/main/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue

#688

### 備考

- このプルリクエストでは、Google翻訳の代わりにDeepL Translateを使用しています。
- このプルリクエストは、翻訳される複数のファイルを含んでいます。

2023-04-23 20:56 UTC, IRod22 commented
😕 なぜビルドが失敗するのかわからない。

2023-04-25 00:37 UTC, nishitaku commented on aio-ja/content/guide/i18n-example.md
> +[Angular Internationalization](AioGuideI18nOverview)ガイドで使用したフランス語のトランスラティモンがあるサンプルアプリケーションを調べるには、<live-example name="i18n" title="live example"></live-example>を参照してください。
リンクのフォーマットが間違ってるのが、エラーの原因だと思われます。
また、翻訳も少し修正しました。

```suggestion
[Angular Internationalization][AioGuideI18nOverview]ガイドで使用しているフランス語翻訳付きサンプルアプリケーションを調べるには、<live-example name="i18n" title="live example"></live-example>を参照してください。
```

2023-04-25 00:37 UTC, nishitaku commented on aio-ja/content/guide/i18n-common-deploy.md
>  # Deploy multiple locales
```suggestion
# 複数ロケールのデプロイ
```

2023-04-25 00:53 UTC, IRod22 commented on aio-ja/content/guide/i18n-common-deploy.md
>  # Deploy multiple locales
キャッチしていただきありがとうございます。

2023-05-18 13:19 UTC, lacolaco requested changes
Thanks for the translation! Please fix the part I commented on.

2023-05-18 13:19 UTC, lacolaco commented on aio-ja/content/guide/i18n-common-deploy.md
> +ワークスペースのビルド設定ファイル[`angular.json`][AioGuideWorkspaceConfig]の`"localize"`オプションに`true`またはロケール ID の配列を指定すると、CLI はアプリケーションのバージョンごとにベース`href`を調整する。
```suggestion
ワークスペースのビルド設定ファイル[`angular.json`][AioGuideWorkspaceConfig]の`"localize"`オプションに`true`またはロケール ID の配列を指定すると、CLI はアプリケーションのバージョンごとにベース`href`を調整します。
```

2023-05-18 13:19 UTC, lacolaco commented on aio-ja/content/guide/i18n-common-deploy.md
> +ワークスペース構築設定ファイル [`angular.json`][AioGuideWorkspaceConfig] に、各ロケールの `"baseHref"` を指定する。
```suggestion
ワークスペース構築設定ファイル [`angular.json`][AioGuideWorkspaceConfig] に、各ロケールの `"baseHref"` を指定しましょう。
```

2023-05-18 13:19 UTC, lacolaco commented on aio-ja/content/guide/i18n-common-deploy.md
> +リモートサーバーにアプリケーションを展開する方法については、[展開][AioGuideDeployment]を参照してください。
```suggestion
リモートサーバーにアプリケーションをデプロイする方法については、[デプロイ][AioGuideDeployment]を参照してください。
```

2023-05-19 10:43 UTC, lacolaco approved these changes

2023-05-19 14:30 UTC, merged