translate: guide/i18n-common-merge
angular/angular-ja pull request #839
Opened 2023-04-24 05:08 UTC by nishitaku

## 翻訳・修正

- [ ] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/main/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue

https://github.com/angular/angular-ja/issues/688

### 備考

2023-04-29 08:42 UTC, lacolaco requested changes
翻訳ありがとうございます！コメントした部分の修正をお願いします :bow:

2023-04-29 08:42 UTC, lacolaco commented on aio-ja/content/guide/i18n-common-merge.md
> +1.  `"localize"`オプションを使って、すべての国際化メッセージを有効な翻訳に置き換え、ローカライズされた variant アプリケーションをビルドします。
```suggestion
1.  `"localize"`オプションを使って、すべての国際化メッセージを有効な翻訳に置き換え、ローカライズされた バリアントアプリケーションをビルドします。
```

2023-04-29 08:42 UTC, lacolaco commented on aio-ja/content/guide/i18n-common-merge.md
> +    variant アプリケーションは、ひとつのロケール用に翻訳された、あなたのアプリケーションの配布可能なファイルの完全なコピーとなります。
```suggestion
    バリアントアプリケーションは、ひとつのロケール用に翻訳された、あなたのアプリケーションの配布可能なファイルの完全なコピーとなります。
```

2023-04-29 08:42 UTC, lacolaco commented on aio-ja/content/guide/i18n-common-merge.md
> +また、他のコンフィギュレーションをオーバーライドするようにプロパティを設定します。
```suggestion
また、他の設定をオーバーライドするようにプロパティを設定します。
```

2023-04-29 08:42 UTC, lacolaco commented on aio-ja/content/guide/i18n-common-merge.md
> +プロダクションビルドの場合は、コンフィギュレーション・コンポジションを使用して両方の構成を実行します。
```suggestion
プロダクションビルドの場合は、設定の合成を使用して両方の構成を実行します。
```

2023-05-01 00:44 UTC, nishitaku commented on aio-ja/content/guide/i18n-common-merge.md
> +完成した翻訳をプロジェクトに統合するには、次の操作を行います
dd26af6 で対応しました。

2023-05-01 01:30 UTC, nishitaku commented
@lacolaco 
コメントありがとうございます。
対応しましたので、ご確認ください。

2023-05-01 12:51 UTC, lacolaco approved these changes

2023-05-01 12:51 UTC, merged