translate: guide/i18n-optional-manage-marked-text
angular/angular-ja pull request #844
Opened 2023-05-02 01:22 UTC by nishitaku

## 翻訳・修正

- [ ] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/main/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue

https://github.com/angular/angular-ja/issues/688

### 備考

2023-05-03 14:38 UTC, lacolaco requested changes
翻訳ありがとうございます！コメントした部分の修正をお願いします :bow:

2023-05-03 14:38 UTC, lacolaco commented on aio-ja/content/guide/i18n-optional-manage-marked-text.md
> +#### ユニークなカスタムIDを定義する
```suggestion
#### ユニークなカスタムIDを定義しましょう
```

2023-05-03 14:38 UTC, lacolaco commented on aio-ja/content/guide/i18n-optional-manage-marked-text.md
> +#### ユニークなカスタムIDを定義する
ここは注意をしている部分なので命令形だとして翻訳しましょう

2023-05-07 11:44 UTC, nishitaku commented
@lacolaco 
コメントありがとうございます。
対応しましたので、ご確認ください。

2023-05-07 12:14 UTC, lacolaco approved these changes
修正ありがとうございます！

2023-05-07 12:15 UTC, merged