translate: tutorial/first-app/first-app-lesson-01
angular/angular-ja pull request #850
Opened 2023-05-13 08:55 UTC by kasaharu

## 翻訳・修正

- [x] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/main/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue

#849

### 備考

2023-05-14 04:04 UTC, kasaharu commented
こっちも記号がフォーマットされていたので直します！

2023-05-14 04:09 UTC, kasaharu commented
79fa9f2 で修正済みです。

2023-05-14 06:07 UTC, lacolaco requested changes
翻訳ありがとうございます！コメントした部分の修正をお願いします :bow:

2023-05-14 06:07 UTC, lacolaco commented on aio-ja/content/tutorial/first-app/first-app-lesson-01.md
> +このレッスンに問題がある場合は、 <live-example></live-example> の完成した確認してください。
```suggestion
このレッスンに問題がある場合は、 <live-example></live-example> の完成したコードを確認してください。
```

2023-05-14 11:05 UTC, kasaharu commented
レビューありがとうございます！suggestion を確認して取り込みました！

2023-05-15 00:41 UTC, lacolaco approved these changes

2023-05-15 00:42 UTC, merged