guide/pipes-transform-dataの和訳作成
angular/angular-ja pull request #910
Opened 2024-02-12 11:46 UTC by darkss-xyzzy

## 翻訳・修正

- [ ] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/main/CONTRIBUTING.md) に記載されたワークフローに従っています

## 関連Issue

https://github.com/angular/angular-ja/issues/754

### 備考

用語の揺らぎがないかを確認していただけますと助かります。
また、pipes-transform-data.mdの14行目、27行目、29行目は翻訳するのに少し悩んだ箇所ですので、
重点的に見ていただけますと助かります。

2024-02-12 13:59 UTC, lacolaco requested changes
翻訳ありがとうございます！コメントした部分の修正をお願いします :bow:

2024-02-12 13:59 UTC, lacolaco commented on aio-ja/content/guide/pipe-template.md
> +パイプはdateをデフォルトフォーマットの**Apr 15, 1988**に変換します。
```suggestion
パイプは日付をデフォルトフォーマットの**Apr 15, 1988**に変換します。
```

2024-02-12 13:59 UTC, lacolaco commented on aio-ja/content/guide/pipe-template.md
> +これは[スタンドアロンコンポーネント](guide/standalone-components)のため、すべての組み込みパイプの源である`@angular/common`から`DatePipe`をインポートします。
```suggestion
これは[スタンドアロンコンポーネント](guide/standalone-components)であるため、すべての組み込みパイプの源である`@angular/common`から`DatePipe`をインポートします。
```

2024-02-12 13:59 UTC, lacolaco commented on aio-ja/content/guide/pipes-transform-data.md
> +"Toggle"ボタンをクリックすることで[沢山の事前に定義されたフォーマット](api/common/DatePipe#pre-defined-format-options)のうち2つである`'mediumDate'`と`'fullDate'`を切り替えることができます。出力は**April 15, 1988**か**Friday, April 15, 1988**です。
```suggestion
"Toggle"ボタンをクリックすることで[たくさんの事前に定義されたフォーマット](api/common/DatePipe#pre-defined-format-options)のうち2つである`'mediumDate'`と`'fullDate'`を切り替えることができます。出力は**April 15, 1988**か**Friday, April 15, 1988**です。
```

2024-02-12 13:59 UTC, lacolaco commented on aio-ja/content/guide/pipes-transform-data.md
> +## 例: 2つのパイプを一緒に変更
ChangingではなくChainingですね
```suggestion
## 例: 2つのパイプを連結する
```

2024-02-12 13:59 UTC, lacolaco commented on aio-ja/content/guide/pipes-transform-data.md
> +これが[スタンドアロンコポーネント](guide/standalone-components)であることを確認するためにクラスファイルに切り替えてください。すべての組み込みパイプの源である`@angular/common`から2つのパイプをインポートしています。
```suggestion
これが[スタンドアロンコンポーネント](guide/standalone-components)であることを確認するためにクラスファイルに切り替えてください。すべての組み込みパイプの源である`@angular/common`から2つのパイプをインポートしています。
```

2024-02-15 12:59 UTC, darkss-xyzzy commented
お待たせしました。
コメントを参照し、修正を行いました。
また、pipes-transform-data.mdの27行目の「表現」ですが、
expressionの和訳「式」に対する揺らぎとなりますので、
「式」に修正しました。

2024-02-17 03:50 UTC, lacolaco approved these changes
ありがとうございます！マージさせていただきます

2024-02-17 03:50 UTC, merged